### ISSUE TITLE
App crashes on contact view

### ISSUE THREAD

**Issue by sawantsingh** [AppLozic/Applozic-iOS-SDK#26]
After going to the contacts list, the following log is coming:
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-09-27 19:22:41.575 ChatApp[837:33518] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fdc826b0fb0 H:[UIImageView:0x7fdc826b0e50(46)]>",
    "<NSLayoutConstraint:0x7fdc826b12e0 H:[UILabel:0x7fdc826b13c0'Navneet Nav'(456)]>",
    "<NSLayoutConstraint:0x7fdc826b1ad0 UIImageView:0x7fdc826b0e50.leading == UITableViewCellContentView:0x7fdc826b0d10.leadingMargin + 10>",
    "<NSLayoutConstraint:0x7fdc826b1b70 UITableViewCellContentView:0x7fdc826b0d10.trailingMargin == UILabel:0x7fdc826b13c0'Navneet Nav'.trailing + 60>",
    "<NSLayoutConstraint:0x7fdc826b1bc0 H:[UIImageView:0x7fdc826b0e50]-(12)-[UILabel:0x7fdc826b13c0'Navneet Nav']>",
    "<NSLayoutConstraint:0x7fdc825e5250 'UIView-Encapsulated-Layout-Width' H:[UITableViewCellContentView:0x7fdc826b0d10(375)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fdc826b12e0 H:[UILabel:0x7fdc826b13c0'Navneet Nav'(456)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-09-27 19:22:41.577 ChatApp[837:33518] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fdc826b4130 H:[UIImageView:0x7fdc826b3fd0(46)]>",
    "<NSLayoutConstraint:0x7fdc826b4460 H:[UILabel:0x7fdc826b4540'applozic'(456)]>",
    "<NSLayoutConstraint:0x7fdc826b4c50 UIImageView:0x7fdc826b3fd0.leading == UITableViewCellContentView:0x7fdc826b3e90.leadingMargin + 10>",
    "<NSLayoutConstraint:0x7fdc826b4cf0 UITableViewCellContentView:0x7fdc826b3e90.trailingMargin == UILabel:0x7fdc826b4540'applozic'.trailing + 60>",
    "<NSLayoutConstraint:0x7fdc826b4d40 H:[UIImageView:0x7fdc826b3fd0]-(12)-[UILabel:0x7fdc826b4540'applozic']>",
    "<NSLayoutConstraint:0x7fdc826b2630 'UIView-Encapsulated-Layout-Width' H:[UITableViewCellContentView:0x7fdc826b3e90(375)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fdc826b4460 H:[UILabel:0x7fdc826b4540'applozic'(456)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by Divjyot** [comment]
Remove the trailing constraint for the Contact Person Name. 
<img width="1280" alt="screen shot 2015-09-28 at 4 20 38 pm" src="https://cloud.githubusercontent.com/assets/14040664/10134010/f8ea7d20-65ff-11e5-811c-42a972af0851.png">
