### ISSUE TITLE
SDWebImage class name conflict if app includes SDWebImage

### ISSUE THREAD

**Issue by brackwasser** [AppLozic/Applozic-iOS-SDK#262]
The Applozic framework includes the SDWebImage source files. If an app includes SDWebImage as well (as I do via CocoaPods), this results in runtime errors like the following:
"Class SDImageCache is implemented in both [Applozic framework] and [my app]. One of the two will be used. Which one is undefined."

**Comment by adarshmishra** [comment]
Now you can use our cocoapod dependency. 
https://cocoapods.org/?q=Apploz

-Thanks
