### ISSUE TITLE
Misc. Additions and Improvements

### ISSUE THREAD

**Issue by Divjyot** [AppLozic/Applozic-iOS-SDK#269]
- [x] 1. Crash for few older user on context chat openings

- [x] 2. Wallpaper for chat background (not currently open to user though)

- [x] 3. Group-Exit button public setter

**Comment by adarshmishra** [comment]
- [ ] send userTypeId parameters in user registration.

**Comment by Divjyot** [comment]
@adarshmishra  DB insertion required of userTypeId parameter?

**Comment by adarshmishra** [comment]
@Divjyot Yes...we need to store in DB for any future use.

**Comment by Divjyot** [comment]
@adarshmishra  as per our latest discussion, wont be saving into DB but only in ALUserDefaults

**Comment by Divjyot** [comment]
- [ ] Add Member option public setter

- [ ] Remove Member options public setter
