### ISSUE TITLE
User Authentication 

### ISSUE THREAD

**Issue by moh1122** [AppLozic/Applozic-iOS-SDK#298]
Hello 
The project is very nice especially the framework from the server side. But I'm facing some problems with user authentication. I did some updates to AppLogicLoginViewController.swift.
The app is always launching the LaunchChatFromSimpleVCViewController.swift even if the user enters a wrong password. then in the launchChatFromSimpleVCViewController it states if the password is wrong or no.
What should be done is that in the AppLogicLoginViewController.swift if users enters the correct pass it should go to the launchChat else it should stay in AppLogicLogin and state that the password is not correct.
Can you help please?
Thank you

**Comment by Abhishek9634** [comment]
it is done

**Comment by Abhishek9634** [comment]
It is a sample project . Observe the login code you will get registerUser method. Comment that line "ALChatManager.registerUser(alUser)" and use " ALChatManager.registerUser(alUser) { (response, error) in  }" and on completion call launchChat class. Run Project  and you problem is solved.

There are 2 methods registerUser  and registerUser with completion
**registerUser**
 This method is used when user is not required to open chat immediately i.e there is more that viewcontrollers chain in login and chat.

**registerUser with completion**
  If user require to open chat Immediately after login

**Comment by devashishmamgain** [comment]
@moh1122 As Abhishek mentioned thats the case only with the sample demo (created for demo purpose).
Here is how the flow will be once you integrate chat sdk in your code:
1. User login to your app, your app does the authentication.
2. After authentication, your app will pass the info to the Applozic login call.
3. For setting up access token from the server side, refer to this link: https://www.applozic.com/docs/configuration.html#access-token-url
4. Based on the access token response, user authentication will work.

**Comment by moh1122** [comment]
thnk u for your reply well I Comment that line "ALChatManager.registerUser(alUser)" and used " ALChatManager.registerUser(alUser) { (response, error) in }" but still the app is launching the LaunchChatFromSimpleVCViewController.swift "Welcome screen" even if i put a wrong password. What i really want is the login screen to stop on AppLogicLoginViewController.swift if the password is incorrect. If it is correct then i want it to enter the screen
Thank you

**Comment by Abhishek9634** [comment]
@moh1122 :have you done this "nd in ALChatManager you will get method "func ALDefaultChatViewSettings" uncomment this ALUserDefaultsHandler.setUserAuthenticationTypeId(1). "
