### ISSUE TITLE
Username issue

### ISSUE THREAD

**Issue by moh1122** [AppLozic/Applozic-iOS-SDK#300]
Hello
There is a username issue also, its not case sensitive. if a user creates a username in capital letters and another user creates a username with lower case any password will work on every user. this is a major issue also, can you please check it. Thank you

**Comment by Abhishek9634** [comment]
@moh1122 : That can be manage from your side also. what ever you store credential in local DB pass that only.

**Comment by moh1122** [comment]
how to pass it ?

**Comment by Abhishek9634** [comment]
@moh1122 : try simple string functions

**Comment by devashishmamgain** [comment]
@moh1122 our system is case sensitive, we will be changing it soon.
In the mean time, what you can do is, once the user login to your app, pass the username to Applozic in lowercase always. This should work.
