### ISSUE TITLE
MB Branch update

### ISSUE THREAD

**Issue by Abhishek9634** [AppLozic/Applozic-iOS-SDK#303]

**Comment by Abhishek9634** [comment]
Removed font and image and most of the images we are using

**Comment by Abhishek9634** [comment]
Images Cleaned

**Comment by Abhishek9634** [comment]
@adarshmishra : I made Changes. Please Pull and and confirm it from your side. 

Thanks

**Comment by priyadarshi** [comment]
- [ ] Login is failing(password is required error coming in log) 
- [ ] Applozic text coming in notification

**Comment by Abhishek9634** [comment]
3. App is crashing for receiving file :: 	d0cbd22

**Comment by Abhishek9634** [comment]
No. 2 Applozic text coming in notification : It is configurable
