### ISSUE TITLE
iOS issue after update

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-iOS-SDK#310]
Ios issue after update

- [x] Run app in background, user conversation view is not opening after click on apns notification 
- [x] Login to app then click on contact and while loading contact click on groups, "Contact person Name" is getting displayed for all group
- [x] APNS notification is not coming if keep app idle for long time
- [x] Sometime Open the conversation list , unread count is not getting updated for user/group
- [x] Loading Indicator Hides in ALChatVC
- [x] User Icon/image issue in group detail view

**Comment by Abhishek9634** [comment]
Login to app then click on contact and while loading contact click on groups, "Contact person Name" is getting displayed for all group : 	065f30e

**Comment by Abhishek9634** [comment]
Run app in background, user conversation view is not opening after click on apns notification : 	6baf571

**Comment by Abhishek9634** [comment]
- [ ] APNS notification is not coming if keep app idle for long time 
NOTE : THIS IS DUE TO NETWORK DELAY **OR** NOT GETTING FROM SERVER

**Comment by Abhishek9634** [comment]
Loading Indicator Hides in ALChatVC / Group detail && MapView Distortion : 5fd2349

**Comment by Abhishek9634** [comment]
Sometime Open the conversation list , unread count is not getting updated for user/group : DUE TO  
CornerRadius it is not showing initially and also case for Profile picture : d84b5ab

**Comment by Abhishek9634** [comment]
User Icon/image issue in group detail view : 3498e08
