### ISSUE TITLE
ALMQTTConversationDelegate not called for custom UIViewController

### ISSUE THREAD

**Issue by shinoys222** [AppLozic/Applozic-iOS-SDK#323]
I wanted to integrate Applozic SDK without the UI functionality provided by the SDK. Found the documentation very little helpful. 

And this piece of code prevents me from using the ALMQTTConversationDelegate sync call from my custom UIViewController.

```
  if([[UIApplication sharedApplication] applicationState] == UIApplicationStateBackground || !top.isOurViewOnTop)
    {
        NSLog(@"Returing coz Application State is Background OR Our View is NOT on Top");
        if ([topic hasPrefix:@"typing"])
        {
            [self subProcessTyping:fullMessage];
        }
        return;
    }

```

How can i get this fixed. As of now i returning true for `isOurViewOnTop` of `ALPushAssistant` to get this fixed. Will it make any future problems ?

**Comment by Abhishek9634** [comment]
@shinoys222 :  if you are using your own views then open same method and add viewControllers Name and for requirements please mails us at support@applozic.com :)

**Comment by shinoys222** [comment]
the above fix works with the sample app. but can't use this with cocoa pods. Also the app crashes when i export the framework from this project.

**Comment by adarshmishra** [comment]
You can go through this post how to add [Applozic framework](https://www.applozic.com/blog/add-applozic-chat-framework-ios/) to your project.

**Comment by shinoys222** [comment]
That helped. thank you :)
