### ISSUE TITLE
Custom user authentication

### ISSUE THREAD

**Issue by giancarlo-soares-beeit** [AppLozic/Applozic-iOS-SDK#331]
Hello,

I'm trying to use my backend api to authenticate my customers. Right now I'm generating my token and sending it back to my app so I can send it to Applozic server. My problem is that I don't know where to pass my token. The documentation says: 'The user should provide the access token in the "accessToken" option while plugin initialization.' but I can't find any property/function to set my token anywhere.
Could you help me with this?
Thanks

**Comment by adarshmishra** [comment]
@giancarlo-soares-beeit you need to do send token as password while doing user registration. Also, make sure you change authentication type to client.
1. Set Authentication type to CLIENT in ALChatManager.m
```
[ALUserDefaultsHandler setUserAuthenticationTypeId:(short)CLIENT];
 ```
2. Set Token as user Password:
```
  [user setPassword:<YOUR ACCESS TOKEN>];
  [ALUserDefaultsHandler setPassword:<YOUR ACCESS TOKEN>];
```

**Comment by giancarlo-soares-beeit** [comment]
Thank you very much for the quick answer, it is working now.
