### ISSUE TITLE
Always getting 0 unreadcount for individual user and groups 

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#334]
I am using code For individual chat as below -->>
                let contactSecvice :  ALContactService = ALContactService()
                let contact = contactSecvice.loadContactByKey("userId", value: String(MemberAppLozicId))
                 print(contact.unreadCount)
I am using code For Group chat as below -->>

              let ChannelService :  ALChannelService = ALChannelService()
              let Channel = ChannelService.getChannelByKey(ChannelKey)
              print(Channel.unreadCount)

**Comment by adarshmishra** [comment]
@Jitendragts,
Can you please send us more detail at support@applozic.com? 
i) Applozic ApplicationId
ii) receiver userId
iii) sender userId (logged-in userId)

Also, just for the cross check make sure you are passing userId as Other user(not logged-in user).

**Comment by Jitendragts** [comment]
Its seems to be working fine now . i didn’t make any change in my code , but doesn’t know how its working fine now .  Still thanks for quick reply :)
