### ISSUE TITLE
change camera view 

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#336]
Can we change camera view with overlay for capturing image and recording video .

**Comment by Jitendragts** [comment]
please reply whether it is possible in sdk or not ?

**Comment by adarshmishra** [comment]
@Jitendragts Yes it is possible as, you can edit framework code and achieve any level of customisations. Here is the [blog](https://www.applozic.com/blog/add-applozic-chat-framework-ios/) explains how you can add framework code to your project.

You can edit **ALChatViewController.m 's openCamera** method and add overlay:

```
 if (granted)
                {
                    self.mImagePicker.sourceType = UIImagePickerControllerSourceTypeCamera;
                    self.mImagePicker.mediaTypes = [[NSArray alloc] initWithObjects: (NSString *)kUTTypeImage, nil];
                    self.mImagePicker.cameraOverlayView = < Your overlayview >
                    [self presentViewController:self.mImagePicker animated:YES completion:nil];
                }
```

If you have any our own controller, below discussion on [stack-overflow](http://stackoverflow.com/questions/41930718/customize-camera-overlay-in-applozic/41932147#41932147) might be helpful. (may be asked by your team  ). 

-Thanks

**Comment by Jitendragts** [comment]
Thanx. Now i can customize code accordingly.
