### ISSUE TITLE
Multiple errors from universal framework when uploading app to appstore

### ISSUE THREAD

**Issue by kiritoxcii** [AppLozic/Applozic-iOS-SDK#339]
In the next screenshot are listed the error I get when try to upload my app to the appstore.
https://drive.google.com/open?id=0B32XT8KzPUxZMVpra2RPN2pndHc

**Comment by kiritoxcii** [comment]
It's not an issue of code, sorry, but the importing tutorial says I should importing the framework as an Embedded Library and it compiles and works but it doesn't work when I try to upload my app to appstore at least for me what worked was to import the frameworsk as a Link Binary with Libraries

**Comment by adarshmishra** [comment]
@kiritoxcii Are you using our bundled framework or added code as target dependency? In case of framework, it might get rejected in approval from apple. Please contact our support (support@applozic.com) with your applozic application-key to get framework signed for your app bundle Id.

**Comment by kiritoxcii** [comment]
Hi, thank you for answering, I just email you the applozic app key
