### ISSUE TITLE
Receiver chat list does not get chat if the receiver hasn't opened the chat, messagesArray comes empty

### ISSUE THREAD

**Issue by kiritoxcii** [AppLozic/Applozic-iOS-SDK#341]
Hi, Are the users not being linked in the get chat list service?

**Comment by adarshmishra** [comment]
@kiritoxcii just after login, sdk will download only latest message for each contact. Historical messages will be downloaded once tapped on contacts. 
Can you please let me know more detail, what you are trying to achieve and what code block you are using?
