### ISSUE TITLE
How can i test if user is exiting in applozics or Not 

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#342]
I need to test if some user is existing or Not . is there any way to get this thing done . Thanx

**Comment by adarshmishra** [comment]
@Jitendragts ,
Do you want to check if this some user exist before logged-in into your application or wanted to check is some other user is present or not after logged-into app?
1) If one user (Say User X) is logged-in to app and trying to check for other user (Say User Y): you can use below method to check:

```
[ALUserService userDetailServerCall:@"<User Y ID>" withCompletion:^(ALUserDetail *alUserDetail) {
        
        if(alUserDetail && alUserDetail.lastSeenAtTime){
            NSLog(@"User present.." );
        }else{
            NSLog(@"alUserDetail not present");
        }
    }];
```
2) If you want to check user presence on applozic before login:

You can check our userdetail api and call it with admin credential. This you need to call form your application server.

Admin API:
[Admin credential](https://www.applozic.com/docs/platform-api-chat.html#application-admin)

User detail API:
[User detail](https://www.applozic.com/docs/platform-api-chat.html#user-details)

**Comment by Jitendragts** [comment]
It worked . Thanx
