### ISSUE TITLE
abc Member added to xyz group , but xyz group is not returning by getAllChannelList()

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#343]
I am adding one member say "abc" in group say "xyz"  by a member say "mnp" . "abc" has successfully added in group as i can see "abc" in "xyz" group from "mnp" 's group list. But after adding "abc" in "xyz" group , i am not getting "xyz" group in "abc" 's group list.

i am using that code to get groups list:-
      let AlChanelServiceObj : ALChannelService = ALChannelService()
      let arrGroups = AlChanelServiceObj.getAllChannelList()

**Comment by adarshmishra** [comment]
@Jitendragts,

once you add a member to a group, new user's device will do group change sync after receiving  notification to device. Make sure you added support for APNS, If not getAllChannelList() will return correct result only if chat screen in foreground.
