### ISSUE TITLE
We are not getting any notification on getting messages for closed app

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#344]
We need the facility to send push notification on getting new messages . But we are not getting any notification after closing app .

**Comment by suren-gts** [comment]
I think there must be some provisioning profile issue . How can i set provisioning profile for applozic sdk so that we can get push notifications .

**Comment by Jitendragts** [comment]
Yes that can be the issue . Please help me to correct it.

**Comment by adarshmishra** [comment]
@Jitendragts push notification is not linked with applozic framework. It is totally depends on your app configuration. 
There might be many reason for this.  You can check this [blog](https://www.applozic.com/blog/push-notification-troubleshooting-guide/). 
Also, make sure you have uploaded apns certificate (distribution and development) both on applozic dashboard. You can check after once configuration is done at our test page below.

https://www.applozic.com/docs/push-notification-test.html

**Comment by Jitendragts** [comment]
I tested App configuration ,its already set as described in doc. If i set same provisioning for applozic sdk , then i am not able to compile code due to same provisioning. Account's trial period also been expired. Is this cause to stop Push Notifications.

**Comment by adarshmishra** [comment]
You can use any of your wild card profile for applozic SDK, as explained it will not effect push notification. have you tested this on our [test notification page](https://www.applozic.com/docs/push-notification-test.html)? what response you getting on test page?

**Comment by Jitendragts** [comment]
I think there was some issue with app trial period . Now its working fine after increasing trial period. :)   . Thanks Adarsh for being so helpfull.
