### ISSUE TITLE
Push Notification's  badge count is incorrect

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#345]
We are getting wrong badge count on getting push notifications. I seen messages then after it i closed the app . Then on sending fresh messages from other user it gives wrong badge count on app icon . It is showing 9 for first message notification.

**Comment by Abhishek9634** [comment]
@Jitendragts :  Can you tell me when you get new message & without tapping on APN i.e tapping on app icon how much count you get on chat list?

**Comment by Jitendragts** [comment]
Chat list count is working fine , but we are getting wrong badge count from push notification. If we send new (1) message , then we are receiving 9 badge count over the app icon on closed app. on opening app, chat list count is one for that user's unseen messages.

**Comment by TimMedcalf** [comment]
@Jitendragts Did you find out what caused this issue? We are having the same problem.
