### ISSUE TITLE
we did not getting notification after some time

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#346]
After fresh registration , we are getting push notification . But after sometime or if move out of app , then push notification are not coming . Is it something like connection cut of with applozic . It works if i again register with same user i.e after logout and login again . Please help me to get rid of it. This issue is badly effecting my whole app. Thanks.

**Comment by adarshmishra** [comment]
There is no connection cut with applozic as such. It might be delayed due your device network connections. Can you please send us detail at support@applozic.com with your applicationId and userId?

**Comment by Jitendragts** [comment]
Can you please tell me how frequent i need to refresh device push token ?

**Comment by adarshmishra** [comment]
Whenever you get a new token registred on device, you should send it to applozic server. Please check this step .
[ send token to server](https://www.applozic.com/docs/ios-chat-sdk.html#a-send-device-token-to-applozic-server-)

**Comment by Jitendragts** [comment]
How Applozic chatting works , means by sockets or push notifications only ?

**Comment by Jitendragts** [comment]
there can be some issues with :

- (void)applicationDidEnterBackground:(UIApplication *)application {

    ALRegisterUserClientService *registerUserClientService = [[ALRegisterUserClientService alloc] init];
    [registerUserClientService disconnect];
    [[NSNotificationCenter defaultCenter] postNotificationName:@"APP_ENTER_IN_BACKGROUND" object:nil];
}

- (void)applicationWillEnterForeground:(UIApplication *)application {

    ALRegisterUserClientService *registerUserClientService = [[ALRegisterUserClientService alloc] init];
    [registerUserClientService connect];
    [ALPushNotificationService applicationEntersForeground];
    [[NSNotificationCenter defaultCenter] postNotificationName:@"APP_ENTER_IN_FOREGROUND" object:nil];
}

As 
 [registerUserClientService disconnect]; 
and
    [registerUserClientService connect];
methods have no code , there is only one line of code there which is also commented.


-(void) connect
{
    //[[ALMQTTService sharedInstance] connectToApplozic];
}

-(void) disconnect {
   // ALMQTTConversationService *ob  = [[ALMQTTConversationService alloc] init];
    //[ob sendTypingStatus:[ALUserDefaultsHandler getApplicationKey] userID:[ALUserDefaultsHandler getUserId] typing:NO];
    
  //  [[ALMQTTConversationService sharedInstance] unsubscribeToConversation];
}

Is this creating that issue ?

**Comment by jlubeck** [comment]
I'm not getting push notifications... how is it supposed to work?
I followed the guide, uploaded my certificates and even tried the certificates with external tools to make sure they work with my app, and they do. But they don't seem to work through your servers...

Thanks

**Comment by adarshmishra** [comment]
Can you please check from this test page, what response you are getting?
[https://www.applozic.com/docs/push-notification-test.html](https://www.applozic.com/docs/push-notification-test.html)

**Comment by jlubeck** [comment]
An Error Response Packet Was Received From The APNS Server: APNS: [1] Invalid Token

**Comment by Jitendragts** [comment]
Has you removed special characters in between token before sending it to applozic ?

**Comment by Abhishek9634** [comment]
For token Parsing please refer : https://www.applozic.com/docs/ios-chat-sdk.html#step-4-push-notification-setup

**Comment by CrypTest** [comment]
The issue isn't still closed. Need help!

**Comment by mukeshthawani** [comment]
@CrypTest Please file an issue with all the details or send it to support@applozic.com. We will look into it.

**Comment by CrypTest** [comment]
I removed didRegisterForRemoteNotificationsWithDeviceToken from app deleagagte file.
And that worked! Thanks to support@applozic.com for helping me!

**Comment by mukeshthawani** [comment]
@CrypTest Glad that we were able to help you.
