### ISSUE TITLE
How can I get the chat list of the people I already chatted with?

### ISSUE THREAD

**Issue by jlubeck** [AppLozic/Applozic-iOS-SDK#347]
I know that If I run 	[chatManager launchChat:self];
I get the chat list and a whole lot more. But I don´t need all that, I only need the chat list, as I need to put it in just a small part of the UI. 

If that is not possible, how could I build it myself? Thanks!

**Comment by adarshmishra** [comment]
@jlubeck you can build your own list view in that case. For how to fetch messages list group by contacts check below. 
https://www.applozic.com/docs/ios-chat-sdk.html#get-latest-messages-from-each-conversation
For real time update, you can observe below notification.
```
 [[NSNotificationCenter defaultCenter]
     addObserver:self selector:@selector(newMessageHandler:) name:NEW_MESSAGE_NOTIFICATION  object:nil];
```
refresh your list in newMessageHandler method.


Other approach, you might think of container view in your view and add view of ALMessagesViewController.m if it suits your UI flow. 

-Thanks

**Comment by jlubeck** [comment]
Awesome! Thanks!

**Comment by jlubeck** [comment]
Hey @adarshmishra, any idea why the NEW_MESSAGE_NOTIFICATION might not be working for me?

I tried implementing the ALMQTTConversationDelegate and updateTypingStatus: is getting called, but when I send a message to the user, that notification is not being called.

The funny thing is that in the console I am seeing MQTT_GOT_NEW_MESSAGE

Any ideas??

Thanks!

**Comment by adarshmishra** [comment]
Looks like mqtt notifications are ignored, as you are on other than chat view. Can you please check after adding your controller view in below settings in ALDefaultChatViewSettings method?

[ALApplozicSettings setMsgContainerVC:@"Your Controller name"];

**Comment by jlubeck** [comment]
yup, that was it! thanks!
