### ISSUE TITLE
How can I make the Group Creation screen only show people I texted with?

### ISSUE THREAD

**Issue by jlubeck** [AppLozic/Applozic-iOS-SDK#349]
I found this piece of code to show the Group Creation screen.

```
	UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Applozic" bundle:[NSBundle bundleForClass:ALChatViewController.class]];
	ALGroupCreationViewController * groupCreation = (ALGroupCreationViewController *)[storyboard instantiateViewControllerWithIdentifier:@"ALGroupCreationViewController"];
	groupCreation.isViewForUpdatingGroup = NO;	
	[fromViewController.navigationController pushViewController:groupCreation animated:YES];

```

But when I get to the screen where I select the contact, it shows every user in my plan. That's not right though . I should be able to add only people the user has already chatted with. How can I do that?

**Comment by adarshmishra** [comment]
@jlubeck By default SDK will fetch all registered contacts or contacts having text with login user/ contacts present in same groups. 

One way you can customise according to your requirements in based on flag in fetchConversationsGroupByContactId method of ALNewContactsViewController.m

```
self.forGroup.intValue == GROUP_CREATION  
//Filter out contacts having only chat among themself from original list 
```
You can use below method to filter out contacts.
```
-(BOOL)isUserHaveMessages:(NSString *)userId
{
    ALMessageService * msgService = [ALMessageService new];
    NSUInteger count = [msgService getMessagsCountForUser:userId];
    return (count > 0);
}
```

**Comment by jlubeck** [comment]
Worked as expected. Thank you!
