### ISSUE TITLE
How can I localized the sdk?

### ISSUE THREAD

**Issue by jlubeck** [AppLozic/Applozic-iOS-SDK#350]
I'm using it for a Spanish app, and even though I see some text on the ALDefaultChatViewSettings the vast majority of the screens are still in English. Is there a way I can localize things?

Thanks

**Comment by jlubeck** [comment]
I can make a pull request if I can at least get directions on how/what to change

**Comment by adamsrosco** [comment]
None of the texts used are localized inside the framework.

**Comment by mukeshthawani** [comment]
https://github.com/AppLozic/Applozic-iOS-SDK/issues/376
