### ISSUE TITLE
Not getting some user's group and chat.

### ISSUE THREAD

**Issue by Jitendragts** [AppLozic/Applozic-iOS-SDK#351]
After register other user in same device , it get registered . But we are not getting groups and chat of same user. Previously some chat and groups was available . 

Response we are getting on creating new channel for the same user returned response as following ->

2017-03-14 11:56:56.676 Applozic : [ALChannelService.m:280] :: ERROR_IN_CHANNEL_CREATING :: Error Domain=Applozic Code=1 "Unable to connect with the server. Check your internet connection and try again" UserInfo={NSLocalizedDescription=Unable to connect with the server. Check your internet connection and try again}
Optional(Error Domain=Applozic Code=1 "Unable to connect with the server. Check your internet connection and try again" UserInfo={NSLocalizedDescription=Unable to connect with the server. Check your internet connection and try again})
2017-03-14 11:56:56.721 Applozic : [ALChannelDBService.m:438] :: NO ENTRY FOUND

Hopefully this response might be useful to track issue we are facing. Thanks

**Comment by adarshmishra** [comment]
@Jitendragts only one user login is allowed at same time. once you register/login other user in same device, you should call logout first. 

```
 ALRegisterUserClientService * alUserClientService = [[ALRegisterUserClientService alloc] init];
 if([ALUserDefaultsHandler isLoggedIn])
    {
        [alUserClientService logoutWithCompletionHandler:^{ 
        }];
    }
```
Also, can you please add more logs from login to creating channel?

**Comment by Jitendragts** [comment]
I am login one user at a time . But this issue is appearing to only for users after their login . One user which facing this issue is 353777777780

**Comment by adarshmishra** [comment]
@Jitendragts Can you please send more logs from login of the user to creating channel at support@applozic.com?
