### ISSUE TITLE
adding pod to pofile

### ISSUE THREAD

**Issue by manjunathgudisi** [AppLozic/Applozic-iOS-SDK#359]
None of the below combinations working for me

pod 'Applozic', '~>3.8'

pod 'Applozic', '~>3.8.1'

pod 'Applozic', '~>3.8.4'

pod 'Applozic', '3.8.1'

pod 'Applozic', '3.8.4'

pod 'Applozic (3.8.1)'

pod 'Applozic (3.8.4)'

pod 'Applozic (= 3.8.1)'

pod 'Applozic (= 3.8.4)'

The only thing is working for me is, 

> pod 'Applozic'
(it is adding 3.6.1 version which is quite old framework)

<img width="989" alt="screen shot 2017-04-20 at 10 18 17 am" src="https://cloud.githubusercontent.com/assets/6059076/25214305/2df80f94-25b4-11e7-92d1-db498031bdfe.png">

**Comment by adarshmishra** [comment]
@manjunathgudisi Just use

```
pod 'Applozic', '~>3.8'

```
Also, make sure you updated your pod.

**Comment by manjunathgudisi** [comment]
after 'pod update' and 'pod install' works fine. Also changed to pod 'Applozic', '~>3.8'. 

Thank you. Now, the frameworks has been added into the project. And, project has below error while compiling it.

error: make directory /Users/myuser/Library/Developer/Xcode/DerivedData/myproj-ckiuwidnicdeszfbldgarfisqary/Build/Products/Debug-iphonesimulator/Applozic/Applozic.framework/en.lproj: File exists
