### ISSUE TITLE
How to add a user and start chatting with him/her? 

### ISSUE THREAD

**Issue by manjunathgudisi** [AppLozic/Applozic-iOS-SDK#360]
Assume, there are 2 friends. F1 and F2. Both have installed the Applozic (sample-swift) app on their iPhones.

Now, F1 wants to chat with F2. In below screen, there is no option to add a user. How do we add this functionality.

- What are the pre-requisites to start the chat? (they both have apps on their phones)
- Just like skype, can we search for users online and send a request to chat with them?
- How do we add a user on this below screen and start chatting with him/her?

![img_3887](https://cloud.githubusercontent.com/assets/6059076/25218083/2ebe9ec6-25c7-11e7-8e8a-82d390206e81.PNG)

**Comment by Abhishek9634** [comment]
Just open the contacts and you will all users associated with your application ID.
NOTE : Only those users will be shown, those who are registered to Applozic via  your application ID

**Comment by adarshmishra** [comment]
@manjunathgudisi Moreover, as you have the information about who all are friends of user x(login user) and who should come in list to chat, you can use our [contacts api](https://www.applozic.com/docs/ios-chat-sdk.html#contacts) to maintain contacts list.
