### ISSUE TITLE
error typedef redefinition with different types in ALRechability class

### ISSUE THREAD

**Issue by bnagarjuna** [AppLozic/Applozic-iOS-SDK#363]
I am integrating Applozic-iOS-SDK with pod file. getting errors in AlRechability class (Typedef redefinition with different types ('void (^)(ALReachability *__strong)' vs 'void (^)(ReachabilityTM *__strong)').

**Comment by mukeshthawani** [comment]
Please specify iOS version (deployment target) and Applozic SDK version.

**Comment by bnagarjuna** [comment]
iOS diployment -9.3 and pod 'Applozic', '~>3.8'

**Comment by bnagarjuna** [comment]
iOS diployment -10.3 and pod 'Applozic', '~>3.8.6. updated.
still getting Typedef redefinition with different types ('void (^)(ALReachability *__strong)' vs 'void (^)(ReachabilityTM *__strong)
