### ISSUE TITLE
Error comes after integration Applozic manually

### ISSUE THREAD

**Issue by iosupendra** [AppLozic/Applozic-iOS-SDK#364]
## Actual Results
"OBJC_CLASS$_ALDBHandler", referenced from:

"OBJC_CLASS$_ALPushNotificationService", referenced from:

"OBJC_CLASS$_ALAppLocalNotifications", referenced from:

"OBJC_CLASS$_ALUtilityClass", referenced from:

"OBJC_CLASS$_ALChannelService", referenced from:

"OBJC_CLASS$_ALConversationService", referenced from:

"OBJC_CLASS$_ALUser", referenced from:

"OBJC_CLASS$_ALChatLauncher", referenced from:

"OBJC_CLASS$_ALChatViewController", referenced from:

"OBJC_CLASS$_ALUserDefaultsHandler", referenced from:

"OBJC_CLASS$_ALRegisterUserClientService", referenced from:

"OBJC_CLASS$_ALMessageService", referenced from:

"OBJC_CLASS$_ALApplozicSettings", referenced from:

"OBJC_CLASS$_ALConversationProxy", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Applozic SDK version: Applozic 3.8.6 Archive

Xcode version: 8.3

iOS version: ?

Dependency manager + version: ?

**Comment by devashishmamgain** [comment]
@iosupendra please specific on what is the error and file the required details in the issue.

**Comment by iosupendra** [comment]
"_OBJC_CLASS_$_ALDBHandler", referenced from:

  "_OBJC_CLASS_$_ALPushNotificationService", referenced from:

  "_OBJC_CLASS_$_ALAppLocalNotifications", referenced from:

  "_OBJC_CLASS_$_ALUtilityClass", referenced from:

  "_OBJC_CLASS_$_ALChannelService", referenced from:

  "_OBJC_CLASS_$_ALConversationService", referenced from:

  "_OBJC_CLASS_$_ALUser", referenced from:

  "_OBJC_CLASS_$_ALChatLauncher", referenced from:

  "_OBJC_CLASS_$_ALChatViewController", referenced from:

  "_OBJC_CLASS_$_ALUserDefaultsHandler", referenced from:

  "_OBJC_CLASS_$_ALRegisterUserClientService", referenced from:

  "_OBJC_CLASS_$_ALMessageService", referenced from:

  "_OBJC_CLASS_$_ALApplozicSettings", referenced from:

  "_OBJC_CLASS_$_ALConversationProxy", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iosupendra** [comment]
please replay me.
i need your assistence in this issue.

**Comment by iosupendra** [comment]
hello adarsh.

**Comment by mukeshthawani** [comment]
Can you tell us how you integrated the SDK? Steps?

**Comment by adarshmishra** [comment]
@iosupendra 

Looks like you are running our archive framework on simulator. Please use our Universal framework.

**Comment by iosupendra** [comment]
you are right.
working on simulator.

but now i am working on real device.
and app crashed and error comes

dyld: Library not loaded: @rpath/Applozic.framework/Applozic
  Referenced from: /var/containers/Bundle/Application/81C66383-05A6-4FC7-A017-F4DC1E22B199/SHMarket.app/SHMarket
  Reason: image not found

**Comment by mukeshthawani** [comment]
Under the target's General tab, in the Embedded Binaries section add the framework.

**Comment by iosupendra** [comment]
Done

now app stop running.

error :- 

PBXCp Error Group
(null): error: make directory /Users/upendrasinghshekhawat/Library/Developer/Xcode/DerivedData/SHMarket-fuugjplwmfitkpghcpxougbdkuzc/Build/Products/Debug-iphoneos/SHMarket.app/Frameworks/Applozic.framework/AppLozic.momd: File exists
(null): error: open /Users/upendrasinghshekhawat/Library/Developer/Xcode/DerivedData/SHMarket-fuugjplwmfitkpghcpxougbdkuzc/Build/Products/Debug-iphoneos/SHMarket.app/Frameworks/Applozic.framework/AppLozic.momd/AppLozic 5.mom: No such file or directory

**Comment by mukeshthawani** [comment]
Check if it is listed twice in the Embedded binaries or Linked frameworks section.

**Comment by iosupendra** [comment]
thanks bro.... 

don't know how it listed twice....?

**Comment by iosupendra** [comment]
please don"t close this chat.

if any other problem comes then i will ping here.

thanks again....bro

**Comment by iosupendra** [comment]
hello
anybody is here..?

**Comment by Aadesh5** [comment]
@mukeshthawani so if I integrate the app loZic I can't run the app on simulator ?

**Comment by mukeshthawani** [comment]
You can run the app on the simulator using Applozic Universal framework and for archive, you have to use Applozic Archive framework.

**Comment by Aadesh5** [comment]
ok thanks @mukeshthawani

**Comment by mobileappdeveloper2019** [comment]
Hello I am also facing the same error in react native app,can you please help me in this matter

**Comment by mobileappdeveloper2019** [comment]
![Screenshot 2019-04-16 at 6 19 33 PM](https://user-images.githubusercontent.com/49679497/56212842-4022b500-6074-11e9-9ef3-bfba50cacbcc.png)


it is showing me this error  @mukeshthawani

**Comment by mukeshthawani** [comment]
@mobileappdeveloper2019 Thanks for sharing the details. We support Cocoapods for installing Applozic in React native. Can you try that and if you are still facing any problem then please file an issue here: https://github.com/AppLozic/Applozic-React-Native-Chat-Messaging-SDK

**Comment by mobileappdeveloper2019** [comment]
yeah previously we have used Applogic and Firebase but as Applogic is using use_frameworks! and on firebase we have to remove it so if we use use_frameworks! then firebase won't work so we need a solution in which we need to enable Applogic manually. Kindly let me know about this issue.

Thanks

[
![Screenshot 2019-04-16 at 7 30 27 PM](https://user-images.githubusercontent.com/49679497/56218378-533a8280-607e-11e9-9a1c-99f82adbee87.png)
](url)

**Comment by rahulvyas** [comment]
> You can run the app on the simulator using Applozic Universal framework and for archive, you have to use Applozic Archive framework.

Can you share a guide to link against simulator and for archive both. So that we can run on both Device and Simulator.

**Comment by rahulvyas** [comment]
Getting error when framework linked manually when creating archive. 
Showing All Errors Only
Bitcode bundle could not be generated because '/Users/sysquare/Desktop/project-name/Applozic.framework/Applozic' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/sysquare/Desktop/project-name/Applozic.framework/Applozic' for architecture arm64

**Comment by mukeshthawani** [comment]
@rahulvyas Please make sure you've removed the Applozic universal framework from the Xcode. After that add the [archive framework](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks/Applozic%207.8.0%20Archive) as described [here](https://docs.applozic.com/docs/ios-chat-sdk#add-framework-manually).

**Comment by rahulvyas** [comment]
> @rahulvyas Please make sure you've removed the Applozic universal framework from the Xcode. After that add the [archive framework](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks/Applozic%207.8.0%20Archive) as described [here](https://docs.applozic.com/docs/ios-chat-sdk#add-framework-manually).

I do not have universal framework. I have added framework manually.

**Comment by mukeshthawani** [comment]
Please add the Universal framework by downloading it from [here](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks/Applozic%207.8.0%20Universal). See if this is working on Simulator, if it's working then remove it and add the [Archive framework](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks/Applozic%207.8.0%20Archive) for archive.

Also, you can generate an Archive version of the Applozic framework as described [here](https://docs.applozic.com/docs/ios-chat-sdk#archive-framework).

**Comment by rahulvyas** [comment]
I have already generated archive framework manually and linked to my project. The only issue is with bitcode enabled my app's archive is failing due to applozic. If I disable Bitcode archive is created successfully.

**Comment by mukeshthawani** [comment]
While generating the framework, make sure you've enabled Bitcode in the Applozic Xcode project.
Also, try adding `-fembed-bitcode` option as shown [here](https://stackoverflow.com/a/32582969/3637751).

**Comment by rahulvyas** [comment]
@mukeshthawani ok Will check and let you know

**Comment by rahulvyas** [comment]
@mukeshthawani Is there any way to generate Universal static framework (1 file with both (Archive /Simulator) architectures) so that we can run on both Device and Simulator ?

**Comment by mukeshthawani** [comment]
@rahulvyas you can use [this `xcframework` file](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks/Release), it will work in simulator and device both.

**Comment by rahulvyas** [comment]
@mukeshthawani Thanks. It worked. Can you also share the command so that from next time onwards I'll generate the framework myself.

**Comment by Sunilkumarr** [comment]
Hello @rahulvyas,
You can check this doc to generate xcframework :
 https://github.com/AppLozic/Applozic-iOS-SDK/blob/master/Docs/XCFramework.md

**Comment by rahulvyas** [comment]
@mukeshthawani @Sunilkumarr Do I need to run command 2 times and copy both folders(ios-arm64_armv7,ios-arm64_i386_x86_64-simulator) into single folder(Applozic.xcframework) ?

**Comment by Sunilkumarr** [comment]
@rahulvyas You need to run those commands one by one first for iOS Device and then next for Simulator then finally run the creating XCFramework command.

**Comment by wazzah-marham** [comment]
error: Resource "/Users/user_name/Library/Developer/Xcode/DerivedData/Marham_Connect-gfmidtwtyrvbyehbnxowrmkglijk/Build/Products/Debug-iphoneos/Applozic/Applozic.framework/Applozic.storyboardc" not found. Run 'pod install' to update the copy resources script.

Hi !

I am getting the error above after integrating ApplozicSwift pod into my project.
Please help.

**Comment by rahulvyas** [comment]
> @rahulvyas You need to run those commands one by one first for iOS Device and then next for Simulator then finally run the creating XCFramework command to create Applozic.xcframework .

Getting error after running XCFramework command in Applozic SDK version 7.11.0

`No 'swiftinterface' files found within '/Users/sysquare/Desktop/Applozic-iOS-SDK/sample-with-framework/archives/ios.xcarchive/Products/Library/Frameworks/Applozic.framework/Modules/Applozic.swiftmodule'.`
