### ISSUE TITLE
Add/Plus button need to show to chat with registered users

### ISSUE THREAD

**Issue by jeelanb** [AppLozic/Applozic-iOS-SDK#366]
Add/Plus button need to show to chat with registered users

## Expected Results
Add/Plus button need to show on click of it in next page it has to display list of registered users so that 
user can chat with registered users.

## Steps to Reproduce
Launch applozic chat screen. No Icon is displayed to view registered user list.

## Code Sample
ALChatManager file we tried by changing values.But no icon is displayed.
Applozic SDK version: ? 3.6

Xcode version: ? 8.2.1

iOS version: ? 10

Dependency manager + version: ?

**Comment by mukeshthawani** [comment]
You can try our sample app. We have a contacts button on top.

**Comment by jeelanb** [comment]
Thanks for the reply.
Yeah i tested sample add button is displayed.
And i have updated to applozic cocoapods to 3.8 version and but still add but is not displayed in our app.
Code Snippet : 
Jaswanth Kumar (jaswanthk@meraevents.com, jaswanthk@newsletters.meraevents.com, jaswanthk@email.meraevents.com)
 [ALApplozicSettings setColorForNavigation:k_Nav_BackGround_Color];
    [ALApplozicSettings setColorForNavigationItem:[UIColor whiteColor]];
   // [ALApplozicSettings setColorForNavigationItem:[MEUtilities infoColourForKey:@"k_Nav_Tint_Color"]];
    [ALApplozicSettings hideRefreshButton:NO];
    [ALUserDefaultsHandler setNavigationRightButtonHidden:NO];
    [ALUserDefaultsHandler setBottomTabBarHidden:YES];
    [ALApplozicSettings setTitleForConversationScreen:@"Chats"];
    [ALApplozicSettings setCustomNavRightButtonMsgVC:NO]; 

Please let us know  if we missed anything.
