### ISSUE TITLE
Hi i need below customise for chatlist screen UI

### ISSUE THREAD

**Issue by vishnu1989** [AppLozic/Applozic-iOS-SDK#368]
![untitled](https://cloud.githubusercontent.com/assets/2758690/26486179/aa976cf0-4217-11e7-9382-ed4b34417337.png)

## Code Sample

Applozic SDK version: ?

Xcode version: ?

iOS version: ?

Dependency manager + version: ?

**Comment by devashishmamgain** [comment]
@vishnu1989 is this the complete customization you need or some part is already customized?

**Comment by vishnu1989** [comment]
Above is my design and i want to make like this.
right now i just integrated your SDK.

**Comment by vishnu1989** [comment]
can i get unread messages count ?
and also some key like "webAdminGroup" = "1" so i will put "Lock" image and i cant delete this group

**Comment by adarshmishra** [comment]
@vishnu1989,

You can check **Message View Controller** in Applozic.storyboard for UI customisations. 
Controller Name: ALMessagesViewController.m

For unread count please check [documentation here](https://www.applozic.com/docs/ios-chat-sdk.html#unread-count). 

To put lock button, what flag you are looking for? To check if logged-in user is a group admin or not you can use below code.

```
 ALChannelUserX *alChannelUserXLoggedInUser =  [channelDBService loadChannelUserXByUserId:channelKey andUserId:[ALUserDefaultsHandler getUserId]];
if(alChannelUserXLoggedInUser.role.intValue == ADMIN)
{

}
```

**Comment by vishnu1989** [comment]
but i cant found Applozic.storyboard because i added you SDK direct

**Comment by adarshmishra** [comment]
you can add framework code as target dependency and make changes. Please follow below blog:

[Add Applozic framework code](https://www.applozic.com/blog/add-applozic-chat-framework-ios/)

**Comment by vishnu1989** [comment]
so can i customise all UI ?
like chatlist screen UI and chatscreen UI ?

**Comment by adarshmishra** [comment]
Yes, once you will add framework code as explained earlier, you will have access to Applozic.storyboard  and other controllers.

**Comment by vishnu1989** [comment]
Thanks :)

**Comment by mukeshthawani** [comment]
@McDreamy You can add our View Controller as container view. Here's the doc for that: https://docs.applozic.com/docs/ios-chat-theme-and-customization#section-container-view

**Comment by McDreamy** [comment]
@mukeshthawani after adding the container view, my tab bar disappear

**Comment by mukeshthawani** [comment]
Normally it should work fine.
You can try this sample app: https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/SampleAppWithTabBar
