### ISSUE TITLE
Getting crash: contextual chat screen

### ISSUE THREAD

**Issue by manjunathgudisi** [AppLozic/Applozic-iOS-SDK#369]
Hi, Please have a look at the attached screenshot. Im getting crash when I click on Back or Done button. What could be the reason?

![simulator screen shot jun 2 2017 10 36 27 pm](https://cloud.githubusercontent.com/assets/6059076/26736558/4735f9c4-47e4-11e7-9eeb-aca28b3d690d.png)

**Comment by devashishmamgain** [comment]
@manjunathgudisi can you share the crash logs?

**Comment by manjunathgudisi** [comment]
I have fixed the crash. What is the purpose of PickerView in this screen. How does this help me.

**Comment by jimmy0804** [comment]
@manjunathgudisi Can I know how did you fix the crash?

**Comment by manjunathgudisi** [comment]
@jimmy0804 

I have used the below code **ALChatViewController.m** file

```
-(void)updateContextInView
{
//added this code to fix the crash
    **if (self.pickerConvIdsArray.count == 0) {
        [self reloadView];
        return;
    }**
    
    [self.mTableView setUserInteractionEnabled:YES];
    [self.sendMessageTextView setHidden:NO];
}
```

**Comment by mukeshthawani** [comment]
https://github.com/AppLozic/Applozic-iOS-SDK/issues/384
