### ISSUE TITLE
Unable To Fetch Contacts 

### ISSUE THREAD

**Issue by badrinathvm** [AppLozic/Applozic-iOS-SDK#370]
## Goals
Unable to Fetch Contacts when we click on Contact Option in Chat Window.

## Expected Results
Need to see the contact which i have already added as part of previous view controller

## Actual Results
Not able to see the contact

## Code Sample

//
//  StartChatViewController.swift
//  Skillz
//
//  Created by Badrinath on 6/3/17.
//  Copyright © 2017 Badrinath. All rights reserved.
//

import Foundation
import UIKit
import Applozic

class StartChatViewController: UIViewController{
    
    @IBOutlet var logoutButton: UIButton!
    
    @IBAction func logoutAction(_ sender: Any) {
       /* let registerUserClientService: ALRegisterUserClientService = ALRegisterUserClientService()
        registerUserClientService.logout { (response, error) in
            
        }
        self.dismiss(animated: false, completion: nil)*/
    }

    @IBAction func launchChatAction(_ sender: Any) {
        let chatManager : ALChatManager = ALChatManager(applicationKey: Utils.MESSAGING_API_KEY as NSString)

        chatManager.registerUserAndLaunchChat(getUserDetail(), fromController: self, forUser:nil)
    }
    
    override func viewDidLoad() {
    }
   
    func addContact(){
        
        let contact: ALContact = ALContact()
        contact.userId = "sp1"
        contact.fullName = "service Provider 1"
        contact.displayName = "sp1"
        
        let contactService: ALContactService = ALContactService();
        contactService.add(contact)
        
        print(contactService.getOverallUnreadCountForContact())
        
    }
    
    func getUserDetail() -> ALUser {
        
        let user: ALUser = ALUser()

        user.userId = userData
        user.password = "1"
        user.displayName = userData
        user.applicationId = ALChatManager.applicationId
        user.email = userName!
        
        print("User Details \(user.userId) \(user.password) \(user.displayName) \(user.applicationId) \(user.email)")
        
        addContact()
        

        return user;
    }
}

//addContact method tries to add a contact to contact service and should list in contacts table view.
Below are the error logs screenshot
<img width="713" alt="screen shot 2017-06-04 at 8 40 01 am" src="https://cloud.githubusercontent.com/assets/1479179/26763573/dfc3d578-4909-11e7-8405-ecc7c48d6fa1.png">

Any help would be greatly appreciated , as we are looking to scale this application.

Applozic SDK version: ? 3.8

Xcode version: ? 8.2.1

iOS version: ? 9.0

**Comment by MEnnabah** [comment]
I'm having the same issue. Any resolutions? @mukeshthawani

**Comment by mukeshthawani** [comment]
@MEnnabah  If you are getting the same error then you need to check if registration was successful or not. Share full logs at support@applozic.com, we will look into it.
