### ISSUE TITLE
Please contact Applozic to activate Chat

### ISSUE THREAD

**Issue by badrinathvm** [AppLozic/Applozic-iOS-SDK#371]
## Goals
I have integrated Applozic sDK to my app. It's asking to please contact applozic to activate chat..

I have my own application key.. Do i need to do anythin to activate ? See the attached screenshot.

## Expected Results
Chat messages should be sent.

## Actual Results
Messages aren't sent.

## Code Sample

![simulator screen shot jun 4 2017 4 12 47 pm](https://cloud.githubusercontent.com/assets/1479179/26766162/aeeba188-4940-11e7-944b-199ae9868ef2.png)

Applozic SDK version: ? 3.8

Xcode version: ? 8.2.1

iOS version: ? 9.0

**Comment by badrinathvm** [comment]
Messages are not getting delivered .. I am using my Beta API Key..

**Comment by devashishmamgain** [comment]
@badrinathvm you must be using the Distribution build for testing.
Free trial application key works only for the development and testing environments.
You can use the Development build for the testing purpose.
For Distribution build (production ready), you can subscribe for the service.

**Comment by badrinathvm** [comment]
Yup, will follow the same @devashishmamgain. Thank you very much..
