### ISSUE TITLE
Include of non-modular header inside framework module 'Applozic'

### ISSUE THREAD

**Issue by badrinathvm** [AppLozic/Applozic-iOS-SDK#372]
## Goals
Unable to compile the project . 

## Actual Results
Include of non-modular header inside framework module 'Applozic'

## Steps to Reproduce
Followed manual installation of adding the framework module to Swift project. when tried to compile facing the below issue as attached in screenshot.

## Code Sample

<img width="1246" alt="screen shot 2017-06-04 at 7 35 02 pm" src="https://cloud.githubusercontent.com/assets/1479179/26768524/4ca19f24-495d-11e7-86dd-b6161a53f6c5.png">

Applozic SDK version: ? 3.8.6

Xcode version: ? 8.2.1

iOS version: ? 9.0

**Comment by badrinathvm** [comment]
Tried below options as well in screenshot , still no luck 
<img width="692" alt="screen shot 2017-06-04 at 7 39 32 pm" src="https://cloud.githubusercontent.com/assets/1479179/26768555/987179ba-495d-11e7-9f66-458e844c2a78.png">

**Comment by mukeshthawani** [comment]
Can you click on the header file and check if the target membership is public

**Comment by badrinathvm** [comment]
checking one sec...

**Comment by mukeshthawani** [comment]
Click on the file inspector button (page icon), where Quick help is coming.

**Comment by badrinathvm** [comment]
Yes did , but i don't see target membership to make it public. Below is screenshot
<img width="901" alt="screen shot 2017-06-05 at 12 18 36 am" src="https://cloud.githubusercontent.com/assets/1479179/26774325/9f76b01e-4984-11e7-882d-9969e39e8a23.png">

**Comment by badrinathvm** [comment]
I was able to see target membership if i select the whole framework but no option for making it public.. It just shows Required. Refer below screenshot.
<img width="1280" alt="screen shot 2017-06-05 at 12 21 33 am" src="https://cloud.githubusercontent.com/assets/1479179/26774428/12c59e9a-4985-11e7-9100-12aa2c3cdeac.png">

**Comment by mukeshthawani** [comment]
Is this happening once you did some changes or from starting?
You added bridging header file or not?

**Comment by badrinathvm** [comment]
previously it was working .. started failing when i tried to archive to test it on device, from then on it's failing continuously even when i try to run on simulator too.. 

Yes i have the bridging file and i have made that public too...
<img width="1263" alt="screen shot 2017-06-05 at 12 32 26 am" src="https://cloud.githubusercontent.com/assets/1479179/26774734/931f0fb2-4986-11e7-93a7-9848dab2cf15.png">

**Comment by mukeshthawani** [comment]
Clean it and then try and if it doesn't work then try deleting the framework and add it again.

**Comment by badrinathvm** [comment]
I tried it several times clean , building and then adding it again.. No luck :(

**Comment by mukeshthawani** [comment]
Please share the project at support@applozic.com

**Comment by badrinathvm** [comment]
sure will do..

**Comment by badrinathvm** [comment]
Sent to support@applozic.com solution for it would really help me a lot in proceeding further in adopting applozic..

**Comment by mukeshthawani** [comment]
Thanks. I will look into it.

**Comment by badrinathvm** [comment]
Really appreciate a lot Mukesh.. Looking forward for the solution.

**Comment by badrinathvm** [comment]
Awesome project now works after removing it from pod.. Thanks again...
