### ISSUE TITLE
**Bugs** ALMapViewController is requesting inUse as well as Always permission.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#373]
## Goals
I want to use the native Location sharing feature.

## Expected Results
To get the location using the inUse permissions and not the background permission, because background permissions are not needed for in app location sharing.

## Actual Results
I am getting my apps background permission access dialog appearing, and because inUse permissions are already enabled, we are able to get the location data.

## Steps to Reproduce
Custom app. If you grant in use permissions and navigate to a Conversation, select attachments, Share location... you will be shown the background access permission, and you get kicked off the location screen.

## Code Sample
ALMapViewController.m

 [self.locationManager requestAlwaysAuthorization];
 [self.locationManager requestWhenInUseAuthorization];

Applozic SDK version: 3.8.6

Xcode version: 8.3

iOS version: 9.3

Dependency manager + version: ?

**Comment by mukeshthawani** [comment]
Hi, right now it is present in the code but it won't ask for Always permission as we have not added that in the Info.plist file. Maybe you have added that in the info.plist that's why it's asking for always permission. Remove it from the info.plist file and it will work.

We will remove it from our code in the future version.

**Comment by adamsrosco** [comment]
Hi Mukesh,

I do have it in my plastic for a very specific reason so cannot simply
remove it. I will have to override the classes and do away with it for now.

Please remove with future release, does not make sense to ask for
background permission when this feature only requires in use permissions.
Thanks.

Regards
Rosco.

On 09 Jun 2017 13:16, "Mukesh Thawani" <notifications@github.com> wrote:

Hi, right now it is present in the code but it won't ask for Always
permission as we have not added that in the Info.plist file. Maybe you have
added that in the info.plist that's why it's asking for always permission.
Remove it from the info.plist file and it will work.

We will remove it from our code in the future version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AppLozic/Applozic-iOS-SDK/issues/373#issuecomment-307362883>,
or mute the thread

**Comment by mukeshthawani** [comment]
Sure

**Comment by adamsrosco** [comment]
Hi,

I see this issue still hasnt been included in the last 2 releases. Can this issue be reopened and addressed.

Regards,
Rosco.
