### ISSUE TITLE
**Feature Request**: Localize Texts in app.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#376]
## Goals
To be able to Translate texts used within the application

## Expected Results
All texts displayed to the user to use the NSLocalization Protocol, so as a user, i can pull all those localizations and have them translated for our application. Right now we are limited to only using the english texts.

## Steps to Reproduce
Texts are all currently just constant strings... i.e.     @"Chat"

## Code Sample
NSLocalizedStringWithDefaultValue(@"AL_Chat", nil, [NSBundle mainBundle], @"Chat", @"Context -  Chat text for chat screen");

**Comment by mukeshthawani** [comment]
We are working on it.

**Comment by adamsrosco** [comment]
Thanks... will keep a lookout.
