### ISSUE TITLE
**Feature Request**: Add Categories to Chat Cells (ALAudio etc), that manage Programatic Autolayout.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#378]
**Feature Request**: Add Categories to Chat Cells (ALAudio etc), that manage Programatic Autolayout.

## Goals
To be able to switch out AutoLayout categories, depending on implementation look and feel.

## Expected Results
To be able to pull in a category with a layout method (built as a strategy... base class with a layout method, which can be subclassed and called by the tableview laying out the cell).

## Code Sample
Create a Category:
ALAudioCell+ALAudioCellCategory.h
ALAudioCell+ALAudioCellCategory.m

override the updateConstraints method.

That way depending on the category imported, you can change the layout of the cell you require.

**Comment by mukeshthawani** [comment]
Hi, we are working on it. We are creating almost all the constraints programmatically so that it becomes easier to change and we will release it in some time.

**Comment by adamsrosco** [comment]
awesome.. will keep a lookout
