### ISSUE TITLE
**Bugs** ALMessageService getLatestMessageForUser returns read messages as unread.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#381]
## Goals
[ALMessageService getLatestMessageForUser] to get a list of unread messages when the user logs into our application.

## Expected Results
Local DB updates with correct status of read/unread

## Actual Results
```objective-c
[ALMessageService getLatestMessageForUser]  returns old messages as Unread. 
[ALUserService getTotalUnreadCount], returns unread count for previously read messages. 
```
## Steps to Reproduce
Call [ALMessageService getLatestMessageForUser] on startup.
Observe unread messages apply.

## Code Sample
```objective-c
[[ALMQTTConversationService sharedInstance] subscribeToConversation];
[[ALMQTTConversationService sharedInstance] setMqttConversationDelegate:self];
[ALMessageService getLatestMessageForUser:[ALUserDefaultsHandler getDeviceKeyString] withCompletion:^(NSMutableArray  * messageList, NSError *error) {
ALUserService * userService = [ALUserService new];
    NSUInteger count = [[userService getTotalUnreadCount] integerValue]; //observe value
                                                               }];
```

Applozic SDK version: latest

Xcode version: 8.2

iOS version: 10.3

Dependency manager + version: cocoapods 1.1.1

**Comment by DixPatel009** [comment]
@adamsrosco i have the same issue. you got any solution for this issue ?

**Comment by adamsrosco** [comment]
Hi,

I havent checked again, but are you calling the logout method? There's a last date time field that gets sent through on the api, that funny enough gets cleared when you call the logout method. 

override that, and you should be ok.

**Comment by adamsrosco** [comment]
@DixPatel009 Did you manage to resolve your issue?
