### ISSUE TITLE
API for Refresh messages in ALMessagesViewController

### ISSUE THREAD

**Issue by manjunathgudisi** [AppLozic/Applozic-iOS-SDK#383]
Hi

## Goals

I need to have refresh (or reload) all the chats when I pull the table view down in **ALMessagesViewController** screen. Whats the API for this.

Below is the code:
```
func launchChatList() {
        let alChatLauncher: ALChatLauncher = ALChatLauncher(applicationId: getApplicationKey() as String)
        alChatLauncher.chatLauncherDelegate = self
        let storyboard = UIStoryboard(name: "Applozic", bundle: Bundle(for: ALChatViewController.self))
        appLozicTabBar = storyboard.instantiateInitialViewController() as? UITabBarController
        let navBAR = appLozicTabBar?.viewControllers?.first as? UINavigationController
        let msgVC = navBAR?.viewControllers.first as? ALMessagesViewController
        msgVC?.messagesViewDelegate = alChatLauncher as! ALMessagesViewDelegate
        appLozicTabBar?.navigationItem.leftBarButtonItem = nil
        self.view.addSubview((appLozicTabBar?.view)!)
        appLozicTabBar?.didMove(toParentViewController: self)
    }
```

## Expected Results

For ex: if someone sent a message to me at very first time (assume Im online), it needs to have a new entry in the chat list.

![img_4140](https://user-images.githubusercontent.com/6059076/27321575-590c8a8c-55b8-11e7-9fb6-c5e23aed61f2.PNG)

## Actual Results
Its not refreshing (or reloading) when I get a new message from someone.

Applozic SDK version: 3.8.6

Xcode version:  8.3.3

iOS version:  iOS10

**Comment by mukeshthawani** [comment]
You can use `refreshMessageList` method in ALMessagesViewController to refresh.
