### ISSUE TITLE
**Bug** ALChatViewController crashes when receiving contextual chat message

### ISSUE THREAD

**Issue by jimmy0804** [AppLozic/Applozic-iOS-SDK#384]
## Goals
Contextual Chat sometimes does not work as expected. I really need this feature to work ASAP, any help would be appreciated.

Note: This happens also on Android SDK

## Expected Results
When User A starts a contextual chat with User B, User B should receive the message with a context.

## Actual Results
When User A starts a contextual chat with User B, User B receives the message without a context, and even worse, the app will crash sometimes.

## Code Sample
The alConversationProxy is nil sometimes.

-(UIView *)getHeaderView {    
    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 84)];

    ALConversationService * alconversationService = [[ALConversationService alloc]init];
    ALConversationProxy *alConversationProxy = [alconversationService getConversationByKey:self.conversationId];
    
    ALTopicDetail * topicDetail = [[ALTopicDetail alloc] init];//WithJSONString:alConversationProxy.topicDetailJson];
    topicDetail = alConversationProxy.getTopicDetail;
    
    // Image View ....
    UIImageView *imageView = [[UIImageView alloc] init];
    NSURL * url = [NSURL URLWithString:topicDetail.link];
    [imageView sd_setImageWithURL:url];

Xcode version: 8.2.1

iOS version: 10.2.1

**Comment by mukeshthawani** [comment]
We will look into it.

**Comment by mukeshthawani** [comment]
Thanks for sharing.
We will fix this in the next release.
