### ISSUE TITLE
**Feature Request** setTitle of ALChatViewController to be Public instead of Private.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#385]
**Feature Request** setTitle of ALChatViewController to be Public instead of Private.

## Goals
I would like to subclass/override the setTitle method to add in my own UI customisations to the navigation bar. 

## Expected Results
for setTitle method to be made public, so i can override/call super on the method while adding in my own elements / modify existing elements.

**Comment by mukeshthawani** [comment]
Can you share the use case?
Title of ALChatViewController is same as the display name of the user or group name.

**Comment by adamsrosco** [comment]
For displaying the group/profile photo in the navigation bar instead of that chat. Or modifying the text layout of the last update /title view.

**Comment by adamsrosco** [comment]
Hi,

Any chance this can be merged?

**Comment by mukeshthawani** [comment]
Done
