### ISSUE TITLE
Unable to send Messages error

### ISSUE THREAD

**Issue by badrinathvm** [AppLozic/Applozic-iOS-SDK#388]
## Goals
Send Messages

## Expected Results

Able to Send Messages

## Actual Results

<img width="612" alt="screen shot 2017-06-22 at 8 39 01 pm" src="https://user-images.githubusercontent.com/1479179/27465871-258a794c-578b-11e7-90a2-d6bc68fff604.png">

attached in screen shot 

Applozic SDK version: ? 3.8

Xcode version: ? 8.2.1

iOS version: ? 9.0

**Comment by badrinathvm** [comment]
I have sent my Xcode project in mail to support@applozic.com. Any small pointer in solving the issue will be very great...

**Comment by adamsrosco** [comment]
Did you register (logon) to the server before sending the message?

**Comment by mukeshthawani** [comment]
Try the updated project that I have sent you. Registration was not done properly.

**Comment by badrinathvm** [comment]
Let me check.

**Comment by adamsrosco** [comment]
You need to create the ALUser object for your user. 

https://www.applozic.com/docs/ios-chat-sdk.html

**Comment by badrinathvm** [comment]
Gotcha.. Is there any way to get the count of no of unread messages ? And also some times messages gets delivered instantly and some times it takes more time .. Does it depends on the load on the beta key ?

**Comment by mukeshthawani** [comment]
Yeah, you can get unread count, check this: https://www.applozic.com/docs/ios-chat-sdk.html#unread-count

Regarding messages please share the details at support@applozic.com like when and for what type of messages it is taking more time.

**Comment by badrinathvm** [comment]
This helps thank you very much Mukesh..

**Comment by adamsrosco** [comment]
If you want a quick badge number when the user logs in, the Registration Response has a unread count in there.

otherwise you need to pull the latest messages, then do the call [alUserService getTotalUnreadCount]; to get the up to date unread count.
