### ISSUE TITLE
Applozic IOS SDK release 3.9.1

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/Applozic-iOS-SDK#394]
- [x] Support for Audio/Video 
- [x] Group APIs for group info based on GroupIds and client groupIds
- [x] Context base chat fix 
- [x] Message input box hight fix

**Comment by adamsrosco** [comment]
Good Morning, 

Are you able to tag and push a cocoapod update please.

**Comment by mukeshthawani** [comment]
Once we release the updated framework, we will push to Cocoapods also.

**Comment by adamsrosco** [comment]
awesome thanks.
