### ISSUE TITLE
** Feature Request ** Move Constants from Implementation file to header in ALRegisterUserClientService.m

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#402]
## Goals
To subclass ALRegisterUserClientService to perform additional actions on Registration and Logout.

## Expected Results
to Sublcass and override without compiler errors

## Actual Results
Getting a compilation error as the defined constants do not exist. Can the defines be moved to the .h file instead?

## Steps to Reproduce

1. Subclass ALRegisterUserClientService.
2. Copy and paste method logoutWithCompletionHandler in Subclassed.m file.
3. Observe : _LOGOUT_URL_ use of undeclared identifier.

## Code Sample

```objective-c

-(void)logoutWithCompletionHandler:(void(^)(ALAPIResponse *response, NSError *error))completion
{
    NSString *urlString = [NSString stringWithFormat:@"%@%@",KBASE_URL,LOGOUT_URL];
    NSMutableURLRequest * request = [ALRequestHandler createPOSTRequestWithUrlString:urlString paramString:nil]; 
    ...
}
```
```python
error: use of undeclared identifier
```

**Comment by mukeshthawani** [comment]
Can you create a PR? We will be happy to merge if it works.

**Comment by adamsrosco** [comment]
Thanks. PR created.
