### ISSUE TITLE
iOS - Hide navigation bar

### ISSUE THREAD

**Issue by zaifz** [AppLozic/Applozic-iOS-SDK#411]
Is there a way to hide the navigation bar of the chat controller?

**Comment by mukeshthawani** [comment]
Right now we don't have any public API to do that. You can add our framework as a target (follow this blog: https://www.applozic.com/blog/add-applozic-chat-framework-ios/) and do the customizations. If you don't want navigation bar then you can present ALMessagesViewController without navigation controller.
