### ISSUE TITLE
** Bug ** Popping ALChatViewcontroller to 3rd party screen results in White Nav Bar.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#416]
## GOAL ## 
Pop the controller and redirect to a new screen.

## Expectation ##
push to new view controller works

## Result ##
Push to new view controller happens, but Navigation Bar loses its Tint Colour value.

## Code ##

Noticed that when popping the ALBaseViewController, the navigationBar's tint colour gets reset, but the variable it gets set too is nil. This results in the navigation bar setting its tint value to white!

```objective-c
-(void)viewWillDisappear:(BOOL)animated
{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"APP_ENTER_IN_FOREGROUND" object:nil];
    self.navigationController.navigationBar.barTintColor = self.navColor;
    
    [self removeRegisteredKeyboardNotifications];
}
```

```self.navColor``` is never set and is ``` nil ```.

**Comment by mukeshthawani** [comment]
Fixed by #417
