### ISSUE TITLE
** Bug ** Third party local notification not displaying correctly

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#418]
## GOAL ## 
Display Local notification on 3rd party screen.

## Expectation ##
Display Local Notification on 3rd party screen, the same as the notification that displays on the chat screens.

## Result ##
Notification displays, but missing User Name.

## Code ##

The information being pushed to TSMessage showNotificationInViewController method is populated incorrectly. The message is passed as the title, and the title is never set. This results in the local notification being displayed without the Username and only the message.

```objective-c
//ALUtilityClass.m

+(void)thirdDisplayNotificationTS:(NSString *)toastMessage andForContactId:(NSString *)contactId withGroupId:(NSNumber*) groupID delegate:(id)delegate
{
   .
   ..
   ...
   
    [TSMessage showNotificationInViewController:top.topViewController
                                          title:toastMessage
                                       subtitle:nil
                                          image:appIcon
                                           type:TSMessageNotificationTypeMessage
                                       duration:1.75
                                       callback:^(void){
        
                                           
                                           [delegate thirdPartyNotificationTap1:contactId withGroupId:groupID];

        
    }buttonTitle:nil buttonCallback:nil atPosition:TSMessageNotificationPositionTop canBeDismissedByUser:YES];
}
```

The showNotificationMethod should pass in the Username variable ``` title ``` as title, and ``` toastMessage ``` as the subtitle.

```objective-c

[TSMessage showNotificationInViewController:top.topViewController
                                          title:title
                                       subtitle:toastMessage
                                          image:appIcon
                                           type:TSMessageNotificationTypeMessage
                                       duration:1.75
                                       callback:^(void){
        
                                           
                                           [delegate thirdPartyNotificationTap1:contactId withGroupId:groupID];

        
    }buttonTitle:nil buttonCallback:nil atPosition:TSMessageNotificationPositionTop canBeDismissedByUser:YES];

```

**Comment by adamsrosco** [comment]
Also when is the next SDK release. We are planning to release immediately, and need to know when the updated SDK will be made available.

**Comment by mukeshthawani** [comment]
Are you creating a PR to fix this issue?

We will release it tomorrow or day after tomorrow

**Comment by adamsrosco** [comment]
I created a PR #418 to fix.
if it can go in that would be awesome. Thanks.

**Comment by mukeshthawani** [comment]
#418 is an issue, not a PR.

**Comment by mukeshthawani** [comment]
You have not created a PR yet

**Comment by adamsrosco** [comment]
PR Created https://github.com/adamsrosco/Applozic-iOS-SDK/compare/hotfix/418_Fix_For_Local_Notification_display

**Comment by adamsrosco** [comment]
Thanks Mukesh!
