### ISSUE TITLE
FR: Add subProcessTextViewDidChange: to header file for method to be subclassed.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#420]
## GOAL ## 
Update the subProcessTextViewDidChange method to handle custom text view height adjustments.

## Expectation ##
subclass subProcessTextViewDidChange: method.

## Code ##

Can we add the subProcessTextviewDidChange: method to the header file so it can be subclassed. The use case I have is to readjust the height and layout of the text bar according to our designs. 

```objective-c
//ALChatViewController.h
-(void)subProcessTextViewDidChange:(UITextView *)textView;
```

**Comment by adamsrosco** [comment]
Hi,

I created a pull request. Can this go in with the next release please.

Regards,
Rosco.

**Comment by mukeshthawani** [comment]
Sure

**Comment by adamsrosco** [comment]
Thanks Mukesh.
