### ISSUE TITLE
A crash while attaching multiple pictures in the conversation.

### ISSUE THREAD

**Issue by osama-taha** [AppLozic/Applozic-iOS-SDK#424]
Applozic SDK version: 4.3.0
Xcode version: xCode 9
iOS version: 11.0.3
video:
https://www.dropbox.com/s/7xcul5qbh6r6jgw/59edb3fb7803c11659022ea9.mp4?dl=0

**Comment by mukeshthawani** [comment]
Can you share the crash log? that will help us a lot

**Comment by osama-taha** [comment]
http://crashes.to/s/cf55143dbcb

**Comment by mukeshthawani** [comment]
It's happening due to "Privacy Violation". Add the below key-value text in the info.plist file:

```
<key>NSCameraUsageDescription</key>
<string>Allow Camera</string>
<key>NSContactsUsageDescription</key>
<string>Allow Contacts</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>Allow location sharing!!</string>
<key>NSMicrophoneUsageDescription</key>
<string>Allow MicroPhone</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Allow Photos</string>
```

**Comment by osama-taha** [comment]
already added...

**Comment by mukeshthawani** [comment]
Then it should work, I don't think there could be any other reason. Can you share a sample app where we can reproduce the issue?

**Comment by mukeshthawani** [comment]
Hi @osama-taha 

Add this new permission requirement in info.plist file:

<key>NSPhotoLibraryAddUsageDescription</key>
<string>Allow write access</string>

**Comment by osama-taha** [comment]
Thanks, I will check it out and let you know.
