### ISSUE TITLE
displayName is replaced with userId

### ISSUE THREAD

**Issue by MEnnabah** [AppLozic/Applozic-iOS-SDK#425]
What am I missing here guys?

![screen shot 2017-10-26 at 12 42 55 pm](https://user-images.githubusercontent.com/16809714/32049042-ce62b598-ba4b-11e7-8029-d4f7670bcca0.jpg)

**Comment by mukeshthawani** [comment]
Is it happening every time?

**Comment by MEnnabah** [comment]
Thanks @mukeshthawani.
How can I disable some attachments and keep the others? Like I want to keep only voice notes and disable everything else like photos, etc.
Also, if I did this, do I still need to provide the keys for unused attachments in info.plist file?

**Comment by mukeshthawani** [comment]
Set `isPhotoGalleryOptionHidden`, `isCameraOptionHidden`, `isSendVideoOptionHidden` and `isLocationOptionHidden` to true to hide other options. Keep the keys in info.plist file.

**Comment by MEnnabah** [comment]
@mukeshthawani I set those methods after registering the user, but it still showing all attachment options:

![screen shot 2017-10-30 at 12 04 29 pm](https://user-images.githubusercontent.com/16809714/32165215-b4862958-bd6a-11e7-81e2-b65d8b378de8.jpg)

**Comment by mukeshthawani** [comment]
As it's not related to this issue, please file a different issue.
