### ISSUE TITLE
Attachment options don't respect hiding methods.

### ISSUE THREAD

**Issue by MEnnabah** [AppLozic/Applozic-iOS-SDK#426]
I'm disabling attachments options and they still show up.

![32165347-21f65256-bd6b-11e7-8c60-056068254591](https://user-images.githubusercontent.com/16809714/32195627-8090a734-bdc6-11e7-8467-87caa4b17af4.jpg)

**Comment by adarshmishra** [comment]
hello @MEnnabah 
You need to hide it via settings first. You are using getters.

```
  let attachmentOptionToHide = [":audio", ":video", ":location", ":shareContact"]
  ALApplozicSettings.setHideAttachmentsOption(attachmentOptionToHide)  
```
Check for more options here:

https://docs.applozic.com/docs/ios-chat-theme-and-customization#section-customizing-attachment-options-

**Comment by MEnnabah** [comment]
Thanks @adarshmishra

**Comment by MEnnabah** [comment]
@adarshmishra I need to hide "BLOCK USER", is there any way I could do it? I can hide share contact and other attachments, but I can't do it for block user.

**Comment by mukeshthawani** [comment]
For block user, you have to use the keyword ":blockUser"

**Comment by MEnnabah** [comment]
@mukeshthawani yes that's what I tried, it's not working.

**Comment by mukeshthawani** [comment]
We will try and get back to you.

**Comment by chucksmith** [comment]
I have the same issue that ":blockUser" doesn't work in this list. I just upgraded to 5.2.0.

**Comment by mukeshthawani** [comment]
Thanks for sharing the details @chucksmith. We found the issue, it will be fixed in the next release.

**Comment by mukeshthawani** [comment]
Fixed
