### ISSUE TITLE
crash: Applozic  -[ALDBHandler persistentStoreCoordinator] + 858

### ISSUE THREAD

**Issue by osama-taha** [AppLozic/Applozic-iOS-SDK#427]
A crash:

Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x182c85348 __pthread_kill + 8
1  libsystem_pthread.dylib        0x182d99354 pthread_kill$VARIANT$mp + 396
2  libsystem_c.dylib              0x182bf4fd8 abort + 140
3  Applozic                       0x105511168 -[ALDBHandler persistentStoreCoordinator] + 858
4  Applozic                       0x1055111a8 -[ALDBHandler managedObjectContext] + 64
5  Applozic                       0x105508034 -[ALContactDBService getAllContactsFromDB] + 180
6  Applozic                       0x1055084f4 -[ALContactDBService getOverallUnreadCountForContactsFromDB] + 68
7  Applozic                       0x10557e7cc -[ALUserService getTotalUnreadCount] + 60
8  PrintOSMobile                  0x104d8242c -[TabBarController displayChatTabBadgeIfNeeded] (TabBarController.m:489)
9  PrintOSMobile                  0x104d7fa3c -[TabBarController viewDidAppear:] (TabBarController.m:74)
10 UIKit                          0x18c59469c -[UIViewController _setViewAppearState:isAnimating:] + 852
11 UIKit                          0x18c61ff4c __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 264
12 CoreFoundation                 0x18310542c -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 76
13 UIKit                          0x18c594848 -[UIViewController _setViewAppearState:isAnimating:] + 1280
14 UIKit                          0x18c61ff4c __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 264
15 CoreFoundation                 0x18304345c -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 144
16 UIKit                          0x18c594848 -[UIViewController _setViewAppearState:isAnimating:] + 1280
17 UIKit                          0x18c63d30c -[UINavigationController viewDidAppear:] + 220
18 UIKit                          0x18c59469c -[UIViewController _setViewAppearState:isAnimating:] + 852
19 UIKit                          0x18c5fe0c8 __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke + 44
20 UIKit                          0x18c5fe064 -[UIViewController _executeAfterAppearanceBlock] + 92
21 UIKit                          0x18c7ec788 _runAfterCACommitDeferredBlocks + 556
22 UIKit                          0x18c7dfb24 _cleanUpAfterCAFlushAndRunDeferredBlocks + 288
23 UIKit                          0x18c56e808 _afterCACommitHandler + 132
24 CoreFoundation                 0x1831138b8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
25 CoreFoundation                 0x183111270 __CFRunLoopDoObservers + 412
26 CoreFoundation                 0x18311182c __CFRunLoopRun + 1292
27 CoreFoundation                 0x1830322d8 CFRunLoopRunSpecific + 436
28 GraphicsServices               0x184ec3f84 GSEventRunModal + 100
29 UIKit                          0x18c5df880 UIApplicationMain + 208
30 PrintOSMobile                  0x104e1812c main (main.m:14)
31 libdyld.dylib                  0x182b5656c start + 4

- Applozic version: latest one.
- iOS: 11.03
- device: iPhone 7 plus.

**Comment by mukeshthawani** [comment]
Thanks for reporting the crash. Can you share more details like when is it happening so that we can reproduce?

**Comment by osama-taha** [comment]
Actually it is not reproducible, it happened four times with two different users.

Every time we open the app we get the number of unread messages..

**Comment by mukeshthawani** [comment]
Share the user details at support@applozic.com. We will look into it.

**Comment by adamsrosco** [comment]
@osama-taha , did you manage to resolve this issue?

**Comment by mukeshthawani** [comment]
Closing this to inactivity. Feel free to open it with more details.
