### ISSUE TITLE
Hide back button item in chat

### ISSUE THREAD

**Issue by MEnnabah** [AppLozic/Applozic-iOS-SDK#429]
Hi

I want to remove the back button item in the chat, however, I tried to:

- setBackButtonHidden to true but nothing happens. I'm not sure if it refers to the conversations list or to the chat.
- I tried also to change it from ALChatViewController.

_Note_: _this setupChat() is called after I launchChatForUser._

![screen shot 2017-11-24 at 7 35 15 am](https://user-images.githubusercontent.com/16809714/33196834-66947086-d0ea-11e7-946d-f496ac41e472.jpg)

**Comment by mukeshthawani** [comment]
To hide the back button in the chat view: In `ALChatViewController.m` add this line: [self.navigationItem setHidesBackButton:YES]; in `viewDidLoad`

**Comment by MEnnabah** [comment]
I did try it. Here is a screenshot:

![screen shot 2017-11-24 at 8 57 04 am](https://user-images.githubusercontent.com/16809714/33198762-a4c34840-d0f5-11e7-95f4-09e671198604.jpg)

**Comment by mukeshthawani** [comment]
My mistake, I thought you are launching it from the list.

What you need to do is: Go to`ALBaseViewController` there's a method named: `setUpTheming` in that method comment the below lines:
```
if(self.individualLaunch)
    {
        [self.navigationItem setLeftBarButtonItem:barButtonItem];
    }
```

**Comment by MEnnabah** [comment]
Working now. Thanks @mukeshthawani
