### ISSUE TITLE
Applozic crash: __57-[UIView(Toast) showToast:duration:position:tapCallback:]_block_invoke.39 + 96

### ISSUE THREAD

**Issue by osama-taha** [AppLozic/Applozic-iOS-SDK#430]
Please take a look at this crash:

http://crashes.to/s/d31c9a6c6a5

# Applozic SDK version: latest
# Xcode version: 9.0.1
# iOS version: 11.1.2

**Comment by mukeshthawani** [comment]
This was fixed
