### ISSUE TITLE
Build errors in XCode - new project - after adding ALChatManager.h/.m

### ISSUE THREAD

**Issue by oyvindvol** [AppLozic/Applozic-iOS-SDK#438]
**Bugs**: 
I have created a new (obj-c) project in XCode. And I have followed the guide for adding the frameworks, and adding the files ``ALChatManager.h``and ``ALChatManager.m``. After adding those two files, my solution can`t build anymore. I get these errors:

````
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ALConversationService", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALMessageService", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALChannelService", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALChatViewController", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALRegisterUserClientService", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALUser", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALChatLauncher", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALUtilityClass", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALApplozicSettings", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALConversationProxy", referenced from:
      objc-class-ref in ALChatManager.o
  "_OBJC_CLASS_$_ALUserDefaultsHandler", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in ALChatManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
## Expected Results
No build errors.

## Actual Results
12 build errors.

## Steps to Reproduce
Clean obj-c xcode project. Include ios-sdk version 4.5.0 Universal like explained in the docs. So far it builds fine. Add files ``ALChatManager.h``and ``ALChatManager.m``. Now there is the 12 build errors.

Applozic SDK version: 4.5.0 Universal

Xcode version: 9.2

iOS version: 11.2.1

**Comment by mukeshthawani** [comment]
You have to add Applozic framework in the project's Embedded binaries section and in Linked frameworks section.

![screen shot 2017-12-21 at 7 33 13 pm](https://user-images.githubusercontent.com/5956714/34258898-0e19d3f4-e686-11e7-8dcf-e126cd21f9c8.png)

**Comment by oyvindvol** [comment]
I have done that.

![screen shot 2017-12-21 at 15 07 31](https://user-images.githubusercontent.com/259427/34258975-b4621f8a-e660-11e7-977b-15875ea8795b.png)

**Comment by mukeshthawani** [comment]
Can you share a sample project which we can check?

**Comment by oyvindvol** [comment]
The sample is soon available here: https://github.com/oyvindvol/applozic-chat-common-ios

Uploading as we speak

**Comment by mukeshthawani** [comment]
Thanks for sharing the project. We can see it's giving some error in compilation. We will try to find out why is it happening.
For now, you can directly add our project as a target dependency. https://www.applozic.com/blog/add-applozic-chat-framework-ios/

**Comment by mukeshthawani** [comment]
We have updated the framework, now it will work fine in a simalator. You can try now.

**Comment by NothingIsAll** [comment]
oh what say
