### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by josjevv** [AppLozic/Applozic-iOS-SDK#440]
## Goals
We use carthage for dependency management in our new app. Can you please add support for that?

Applozic SDK version: 4.6

Xcode version: 9.2

**Comment by mukeshthawani** [comment]
We will try to add it but it might take some time, till then you can directly add our project as a target dependency. https://www.applozic.com/blog/add-applozic-chat-framework-ios/

**Comment by mukeshthawani** [comment]
We will look into it and, see if we can add it as a framework.
