### ISSUE TITLE
Push Notification Status: Not Valid

### ISSUE THREAD

**Issue by MEnnabah** [AppLozic/Applozic-iOS-SDK#454]
Hi

One week ago, I did setup push notifications in my app, and it was working fine. I tested it with your [Push Notification Test Web Page](https://www.applozic.com/docs/push-notification-test.html). I was receiving the push notifications.

Today, I've archived the project to publish it to the App Store. After archiving, I tried the push notification with the TestFlight version, and it never worked. 

![screen shot 2018-03-04 at 5 04 13 am](https://user-images.githubusercontent.com/16809714/36941689-be0f358a-1f69-11e8-9b75-ab537df9e8a0.jpg)

I tried on different devices, iOS versions and tried to send a notification to the development version. Never worked.

I sent the logs to your support e-mail: support@applozic.com

**Comment by devashishmamgain** [comment]
Can you verify if both development and distribution certificates are uploaded in Applozic dashboard.
https://support.applozic.com/article/8inD2Vp5Di-how-to-setup-push-notifications
