### ISSUE TITLE
login user again after ALRegisterUserClientService().logout

### ISSUE THREAD

**Issue by MEnnabah** [AppLozic/Applozic-iOS-SDK#456]
Hi

I log out the user after each chat session (our app model requires that) by calling `ALRegisterUserClientService().logout`.

If the user ended the session and started a new chat session, the remote notification while app in the background is not received.

I tried to call `UIApplication.shared.registerForRemoteNotifications()` with the start of each session, but this didn't work either.

Is there any Applozic public API method to `login` the user again?, or maybe any solution I can do?

**Comment by mukeshthawani** [comment]
Hi,
I understand what you are trying to do. What you need to do is, after every logout you will have to login again then it will work fine. All different cases will be handled in that case.

**Comment by mukeshthawani** [comment]
Closed due to inactivity.
