### ISSUE TITLE
Framework in master compiled with beta Xcode (Swift 4.1)

### ISSUE THREAD

**Issue by ramonpoca** [AppLozic/Applozic-iOS-SDK#460]
## Goals
Build a sample app

## Expected Results
Binary Framework being compiled for swift 4.0

## Actual Results

<unknown>:0: error: module compiled with Swift 4.1 cannot be imported in Swift 4.0.3: .../Applozic 5.2.0 Universal/Applozic.framework/Modules/Applozic.swiftmodule/x86_64.swiftmodule

## Steps to Reproduce
Use the Universal Framework in `master`

## Code Sample

Applozic SDK version: 5.2.0

Xcode version: Version 9.2 (9C40b)

iOS version: NA

Dependency manager + version: (Carthage would be nice) ;)

**Comment by ramonpoca** [comment]
Note that the integration document points you to download the frameworks from there.
(https://docs.applozic.com/docs/ios-chat-sdk).

**Comment by mukeshthawani** [comment]
Hi @ramonpoca 

Thanks for sharing the details. We will share the framework which was created using Xcode 8.2. That should work fine.

**Comment by mhrpatel12** [comment]
@ramonpoca Please use this framework. It should work fine.
[Applozic 5.2.0.zip](https://github.com/AppLozic/Applozic-iOS-SDK/files/1825243/Applozic.5.2.0.zip)
