### ISSUE TITLE
Device is still receiving push notification after logout

### ISSUE THREAD

**Issue by SSamanta** [AppLozic/Applozic-iOS-SDK#461]
## Bug
The device is still receiving the push notification after logout.

## Expected Results
After logout from chat device should not be receiving the push notification messages. 

## Actual Results
As a chat user, I did log out of my device and still receiving chat messages via push notification.

## Steps to Reproduce
1. Login 
2. Logout.

## Code Sample
```
let registerUserClientService: ALRegisterUserClientService = ALRegisterUserClientService()
        registerUserClientService.logout { (response, error) in
            if(error == nil && response?.status == "success") {
                print("Logout success")
            } else {
            }
        }
```

Applozic SDK version: 5.2.0

Xcode version: 9.2

iOS version: 11.2.3

Dependency manager + version:

**Comment by adamsrosco** [comment]
Hi @SSamanta,

Logging out is not a valid use case for stopping push notifications. I would recommend you set the push notification flag to "NO" on the update profile call, then call Logout.

**Comment by SSamanta** [comment]
@adamsrosco  I did not understand why it's not the valid case! 

I will try to explain few test case scenario. 

Let consider **John** has 2 devices iPhone and iPad. He logged on his iPhone and iPad both. Now he logged out from his iPhone and still receiving a chat message notification from his contacts on his iPhone but it should not as John did log out from his iPhone. However, if I do update profile call with push notification NO then iPad will not receive push notification message from his contacts, but John is already logged in on his iPad.

**Comment by adamsrosco** [comment]
@SSamanta I understand your use case. It is my understanding that the push notifications get sent to the last device that logged in. Otherwise @mukeshthawani could assist with a feature request. 

The problem is that if you logout, AL will have to remove the Push Token associated with the UDID for that account. 

But question? does AL allow for multiple device push notifications? I was under the impression you can only log in and chat on which ever device you last logged in with?

Therefore if you are chatting on your iPhone, your ipad wont get push notificaitons or new messages.

**Comment by SSamanta** [comment]
@adamsrosco Ok. @mhrpatel12 @mukeshthawani What is logic in AL right now? is it not supporting multiple device push notification? Can you please let us know how it should work on the latest release?

**Comment by adarshmishra** [comment]
@SSamanta We do support multi-device and push token are managed for each device separately. Once you do a logout from device, pushtoken will be nullified for that particular device. 

What I suspect is, it might be happening if notifications are on the way for last sent messages and you do a logout in between. If that is not the case, logout call might be failing for your app. Would you please add complete logs once you do a logout?

**Comment by SSamanta** [comment]
@adarshmishra Thanks for the clarification. I already sent all log details to support desk. Can you please check with @mhrpatel12
