### ISSUE TITLE
**Feature Request**: Tap to see latest messages Button

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#467]
## Goals
Users would like to scroll to past messages and/or attachments to view them and read/see the context around those messages.

## Expected Results
When you scroll back to view an image attachment, once you have viewed the attachment, when you return to the message list, to be able to scroll either up or down to view the messages around that attachment. And when when you are done, tap a button to see the latest messages. Currently everytime you complete viewing an attachment the screen automatically scrolls to the bottom (latest message) {Similiar to whatsapp}

See green highlighted circle on attached image for reference.

## Steps to Reproduce

Applozic SDK version: 5.3.0

Xcode version: 9.2

iOS version: 11.2
![screen shot 2018-04-09 at 07 58 31](https://user-images.githubusercontent.com/2970598/38481806-d53b6e5c-3bcc-11e8-8cbf-f16437586c72.png)

**Comment by mhrpatel12** [comment]
Thank you Adam for your request. 
Autoscroll to bottom after viewing an attachment is a bug. We will include a fix for this in our upcoming release. 
We are also working on Adding a button for scrolling down to bottom. However, it will take some time as we are including multiple scenarios like making it visible only when a new message arrives, number of new messages.
