### ISSUE TITLE
Adding list of contacts will block the UI

### ISSUE THREAD

**Issue by ShaymaAAZ** [AppLozic/Applozic-iOS-SDK#469]
When try to add list of contacts to the Core data , calling addListOfContacts or addContact will block the UI until its done , so If we have a list of 1000 contacts it will block the UI for few seconds,
and when try to add the contacts in background it will crash on managedObjectContext since its in the main context and can't be used in multiple threads.
So I want to be able to add list of contacts without blocking the UI.

Here is my method for adding list of contacts: 

-(void)updateContacts:(NSArray *)contacts {
    ALContactDBService *dBContactService dBContactService = [[ALContactDBService alloc] init];
    [dBContactService purgeAllContact];
    [dBContactService addListOfContacts: contacts];
}
Calling this method will block my UI for few second
-(void)getContactList {
//code to get the contact list from the server and save it in myContacts 
   [self updateContacts:self.myContacts];
}
and when I call it in the background it will crash on managedObjectContext :
-(void)getContactList {
//code to get the contact list from the server and save it in myContacts 
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
               [self updateContacts:self.myContacts];
});
}

Maybe I'm adding the contacts in a wrong way, If yes please tell me what I can do to prevent this behavior ?

Applozic SDK version: latest version
Xcode version: 9.2

**Comment by mhrpatel12** [comment]
Hi @ShaymaAAZ we're looking into this. Will update you soon.
