### ISSUE TITLE
iOS not receiving new messages

### ISSUE THREAD

**Issue by datanotion** [AppLozic/Applozic-iOS-SDK#475]
## Issue Summary
Message list is inconsistent on iOS (works fine on Android).

- I have 2 emulators, iOS and Android.
- When I send a message from iOS, it is received by the Android device
- When I reply from the Android device, it is NOT received by the iOS device
- When I tap on the refresh button on iOS, the messages are shown, but out of order
- Restarting the chat on iOS does not fix the problem
- Logging out/in on the iOS device does not fix the problem
- Restarted the device/app on iOS and the problem still exists
- Tested on a hardware device (iPad), same issue
- Logged in on an Android device (same user) and it works just fine

## Goals / Expected Results
For iOS to show messages without a manual refresh, and in order

## Actual Results
Messages do not show on an iOS device

## Steps to Reproduce / Code Sample
This is just an empty app with nothing more than logging in the user, and calling the launchChat() method. I can provide the entire app if needed, but its simple to reproduce.

**Applozic SDK version:**
Latest NativeScript: `pod 'Applozic', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'nativeScript'`

**Xcode version:** 9.3.1

**iOS version:** Multiple - tested on latest iOS 10 and 9.3.5

***

#### Sending but not receiving
<img width="834" src="https://user-images.githubusercontent.com/4722782/40793078-bba5a952-64b8-11e8-842a-d19eb6259202.png">

#### After a forced refresh
<img width="827" src="https://user-images.githubusercontent.com/4722782/40793145-e2fcb8d8-64b8-11e8-8d50-36c4c50762e7.png">

#### Exiting/reentering the chat, replies still not received
<img width="836" src="https://user-images.githubusercontent.com/4722782/40793181-f711829a-64b8-11e8-8216-132ceadbf99f.png">

#### Logout/Login - all messages now show, but replies are still not recieved
<img width="834" src="https://user-images.githubusercontent.com/4722782/40793204-0707ad50-64b9-11e8-806f-088338c49da2.png">

<img width="830" src="https://user-images.githubusercontent.com/4722782/40793224-14bf1b5e-64b9-11e8-98dc-8078bf0bcd55.png">

#### Full device/app restart - replies still not received
> And notice the strange time-stamp it received - 4:50am when this is continuous testing
<img width="831" src="https://user-images.githubusercontent.com/4722782/40793245-26711dca-64b9-11e8-8ebe-a6e8323e96d8.png">

#### Testing as same user on iPad hardware device - replies not received
![image](https://user-images.githubusercontent.com/4722782/40793541-e9a32626-64b9-11e8-9ee8-aff80912630d.png)

#### Testing as same user on Android (emulator and physical device) - success - messages ARE received
<img width="350" src="https://user-images.githubusercontent.com/4722782/40793296-497d6e4a-64b9-11e8-8eef-17ae1eaa9cf1.png">
<img width="350" src="https://user-images.githubusercontent.com/4722782/40793319-5b51bb62-64b9-11e8-9916-2b7fdead27c6.png">

**Comment by datanotion** [comment]
Just noticed another issue - note the timestamp on the `Reply 5` message image after the device restart - it states 4:50am even though these tests are all being done at the same time.  It fixes itself later, back to 9:21am as it should be.

**Comment by Sunilkumarr** [comment]
@datanotion Checked with the sample  https://github.com/AppLozic/Applozic-NativeScript-Chat-Plugin it works fine which is pointing  to ```pod 'Applozic', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'nativeScript' ```  i'm able to receive a messages once sent from ios to ios or android to ios  . Can you share some logs from Xcode by opening  the chat list screen method ```launchChat()``` and   Also share us your applicationKey and one login userId ?

**Comment by Sunilkumarr** [comment]
Just noticed another issue - note the timestamp on the Reply 5 message image after the device restart - it states 4:50am even though these tests are all being done at the same time. It fixes itself later, back to 9:21am as it should be.    **--> This issue your facing in android or ios ?**

**Comment by datanotion** [comment]
@Sunilkumarr - looking above, the timestamp issue seems to be coming from the Android side.  Ignore that and I will open a ticket on the Android side. 

On your other request, is there a place I can securely send you the information you requested?  I can send you the entire test app so you can see what I am seeing.

**Comment by Sunilkumarr** [comment]
@datanotion Send us the project at support@applozic.com with test users for login

**Comment by datanotion** [comment]
@Sunilkumarr, I ran the same test app today on the same devices, and it runs just fine --- I cannot replicate the issue I was seeing in iOS a few days ago.  I'm going to assume it was related to a different problem that has been solved elsewhere, and close this ticket.  Thank you for your help!
