### ISSUE TITLE
New group member can able to see old messages in that group

### ISSUE THREAD

**Issue by raviteja11b** [AppLozic/Applozic-iOS-SDK#476]
**Bugs**: New group member can able to see old messages in that group
we have tried with public and private type

![screenshot_2018-06-15-17-55-48-640_in brongo brongo_broker](https://user-images.githubusercontent.com/13586484/41468140-87b60de8-70c6-11e8-80dc-4de4fbe7bb10.png)

**Comment by mukeshthawani** [comment]
Currently, this is how it works. In future, we might give an option to hide the previous messages for new users. I will share this with the team.

**Comment by mukeshthawani** [comment]
I am sorry to hear that we do not fit requirements. We currently do not have this in our road-map, however, I will update you once we plan to add this in our future release based on the demand. For more, you can reach out at support@applozic.com
