### ISSUE TITLE
Not receiving push notification when app is active

### ISSUE THREAD

**Issue by McDreamy** [AppLozic/Applozic-iOS-SDK#477]
Hi,

I'm able to receive push notification when app is in background and foreground but I'm not able to receive push notification when app is active and applozic chat list is not launch. Push notification is received when the applozic chat list is launched.

Strangely, I was able to receive push notification when app is active and applozic chat list is not launch in debug mode.

How can I solve this issue? Thank you.

**Comment by Sunilkumarr** [comment]
Can you share us sample project? and its working in debug mode not in release mode?

**Comment by McDreamy** [comment]
I found that my project setting is being reset, after update pod
After enable the background mode, the problem solved.
Thank you.
