### ISSUE TITLE
In ALChatViewController all messages 'to' attribute equal to my current userId.

### ISSUE THREAD

**Issue by mano1337o** [AppLozic/Applozic-iOS-SDK#478]
Hey there,

From the Dashboard, under the messages section, I correctly see the 'From' and 'To' values for the messages of my app. 'From' referring to the sender, 'To' the receiver.

However, in ALChatViewController.m, I am looping through the messages from the tableview's willDisplayCell method and all the ALMessage have their .to attribute equal to my current userId. 
Even when the message was sent by the current user to another user, where I was expecting a different value for the 'to' attribute. 

I am wondering if that's the expected behavior ?

Here's an example by code:
-(void)tableView:(UITableView *)tableView willDisplayCell:(nonnull UITableViewCell *)cell forRowAtIndexPath:(nonnull NSIndexPath *)indexPath {
    NSArray *messagesArray = [[NSArray alloc] initWithArray:[self.alMessageWrapper getUpdatedMessageArray]];
    ALMessage *currentMessage = messagesArray[indexPath.row];
    NSLog(@"currentMessage.to:%@", currentMessage.to); //Always displays the same value: current userId
}

My goal here is to get info about the sender of 'currentMessage', I am currently using metadata but feels like it's the wrong approach.

**Comment by mukeshthawani** [comment]
This shouldn't be happening. Can you share the logs when you login first time and once the message loading has been finished?

Share all the logs at support@applozic.com

**Comment by mano1337o** [comment]
Actually, now I see all the ALMessage.to attribute equal to the other participant in a 1on1 chat but I would expect the "to" attribute to be equal to the current logged in user when the message was sent by the other participant.

Am I misunderstanding something ?

The logs have been sent to support@applozic.com.
