### ISSUE TITLE
Update username 

### ISSUE THREAD

**Issue by McDreamy** [AppLozic/Applozic-iOS-SDK#479]
The current issue I'm facing is when the user updates his username in the app, Applozic chat still display the old username. Is there a way to update the username in Applozic chat without logout and login again to the app?

Thank you.

**Comment by mukeshthawani** [comment]
@McDreamy Yes, this is how it works. Details will be updated without you having to logout and login. Can you explain how you've added our View Controller? As a container view or you're presenting it?

**Comment by McDreamy** [comment]
@mukeshthawani, I launch the chat list by presenting the view controller. The details will not update in the Applozic chat without logout and login.

**Comment by DevShourya** [comment]
Hello @McDreamy,
Currently, the user's display name is not updated in real time for the user. We'll change this in a future release.

**Comment by McDreamy** [comment]
@DevShourya 
I used the following method to update the user display name
`ALUserService *userservice = [[ALUserService alloc] init];

[userservice updateUserDisplayName:displayname andUserImage:imageLink userStatus:nil withCompletion:^(id theJson, NSError *error) {

}];`

The username is not updated in ALMessagesViewController unless I clicked into ALChatViewController and return to ALMessagesViewController

![simulator screen shot - iphone 8 plus - 2018-08-09 at 10 26 44](https://user-images.githubusercontent.com/9667496/43874665-a248956c-9bbf-11e8-8b3e-fe5c9346d8b6.png)
![simulator screen shot - iphone 8 plus - 2018-08-09 at 10 26 48](https://user-images.githubusercontent.com/9667496/43874666-a298ff5c-9bbf-11e8-92a6-78381741d991.png)
