### ISSUE TITLE
How to update members in the group?

### ISSUE THREAD

**Issue by kbokdia** [AppLozic/Applozic-iOS-SDK#480]
## Goals

I want to update members in the group. How should I go about? I have already used ALChannelService to update channel, But could not find a way to update members in that channel.

## Code Sample

Applozic SDK version:  5.10.0

Xcode version: 9.4.1

iOS version: 11.4.1

**Comment by mukeshthawani** [comment]
Hi @kbokdia 

You can use `addMemberToChannel` and `removeMemeberFromChannel` methods present in `ALChannelService`.

Here are the doc links for the same:
https://docs.applozic.com/docs/ios-group-chat-sdk#section-add-user-to-channel-group
https://docs.applozic.com/docs/ios-group-chat-sdk#section-remove-user-from-channel-group
