### ISSUE TITLE
Not getting the message in the chat after successfully sending to the server

### ISSUE THREAD

**Issue by najeeburrehman-brainx** [AppLozic/Applozic-iOS-SDK#484]
I am using the custom UI. I have integrated the push notifications correctly. The problem I am facing in using the applozic SDK is that when I send message to some group or user. The message sends to the applozic server but the local DB not get updated. When I came to the chatViewController by going back to chats list screen I dont get the message sended by me. I thought that the local DB not get updated because when the chatViewController opens from the chats list screen it only gets the data from the local DB.

## Goals
I just need to get the updated message list.

## Code Sample
- Below are the sendMessage button action and the helper method the action is using. 

@IBAction func sendMessageAction(_ sender: UIButton) {
    
        let msg = getMessageToSend()
        self.alMessagesArrayWrapper.addALMessage(toMessageArray: msg)
        self.tableView.reloadData()
        self.sendMessage(messageToSend: msg)
        
    }
func sendMessage(messageToSend: ALMessage) {
        ALMessageService.sendMessages(messageToSend, withCompletion: { message, error in
            if let error = error {
                print(error)
            }
            ALMessageService.addBroadcastMessage(toDB: messageToSend)
            self.tableView.reloadData()
        })
    
    }

Applozic SDK version: 5.12.0

Xcode version: 9.4

iOS version: 11.4

**Comment by Sunilkumarr** [comment]
Can you share us the complete  logs once you send a message?

**Comment by najeeburrehman-brainx** [comment]
Hi there,
If I got you right. When I send the message the console is show the below messages. 

{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
2018-09-04 20:14:36.721254+0500 HowICompare[4599:1223343] <ALMessageService.m:281> message not in DB new insertion.
2018-09-04 20:14:36.724263+0500 HowICompare[4599:1223343] <ALRequestHandler.m:69> POST_URL :: https://apps.applozic.com/rest/ws/message/v2/send
2018-09-04 20:14:36.725431+0500 HowICompare[4599:1223343] <ALRequestHandler.m:117> Basic string...Basic bmFqZWViVXNlcklkOjNmZjFiZmIyLTU5OGUtNGZhNS05OWJhLTVlNTkxNjIyZjQxOQ==
2018-09-04 20:14:38.312288+0500 HowICompare[4599:1223343] <ALAPIResponse.m:25> self.generatedAt : 1536074077990
2018-09-04 20:14:38.313217+0500 HowICompare[4599:1223343] <ALAPIResponse.m:26> self.status : success
Received notification With Completion :: [AnyHashable("AL_VALUE"): {"id":"375f67e106524dfbaa6152f1897e8c641","type":"APPLOZIC_02","message":"AL_GROUP:11434597:najeebUserId","notifyUser":true,"totalUnreadCount":0,"sendAlert":false,"messageMetaData":{}}, AnyHashable("aps"): {
    "content-available" = 1;
}, AnyHashable("AL_KEY"): APPLOZIC_02]
2018-09-04 20:14:43.655046+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:46> APNS_DICTIONARY :: {
    "AL_KEY" = "APPLOZIC_02";
    "AL_VALUE" = "{\"id\":\"375f67e106524dfbaa6152f1897e8c641\",\"type\":\"APPLOZIC_02\",\"message\":\"AL_GROUP:11434597:najeebUserId\",\"notifyUser\":true,\"totalUnreadCount\":0,\"sendAlert\":false,\"messageMetaData\":{}}";
    aps =     {
        "content-available" = 1;
    };
}
2018-09-04 20:14:43.655536+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:47> UPDATE UI VALUE :: 1
2018-09-04 20:14:43.655852+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:48> UPDATE UI :: ACTIVE
2018-09-04 20:14:43.656126+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:38> APNs GOT NEW MESSAGE & NOTIFICATION TYPE :: APPLOZIC_02
2018-09-04 20:14:43.661163+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:120> APNS: APPLOZIC_02 ARRIVED
2018-09-04 20:14:43.661787+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:129> 
Notification Message:AL_GROUP:11434597:najeebUserId

DeviceString:3ff1bfb2-598e-4fa5-99ba-5e591622f419
2018-09-04 20:14:43.662160+0500 HowICompare[4599:1223343] <ALMessageClientService.m:381> LAST SYNC TIME IN CALL :  1536074056469
2018-09-04 20:14:43.662494+0500 HowICompare[4599:1223343] <ALRequestHandler.m:34> GET_URL :: https://apps.applozic.com/rest/ws/message/sync?lastSyncTime=1536074056469
2018-09-04 20:14:43.662932+0500 HowICompare[4599:1223343] <ALRequestHandler.m:117> Basic string...Basic bmFqZWViVXNlcklkOjNmZjFiZmIyLTU5OGUtNGZhNS05OWJhLTVlNTkxNjIyZjQxOQ==
2018-09-04 20:14:44.001296+0500 HowICompare[4599:1223343] <ALMessageClientService.m:398> LATEST_MESSAGE_JSON: {
    deactivated = 0;
    lastSyncTime = 1536074056469;
    messages =     (
    );
    regIdInvalid = 0;
}
2018-09-04 20:14:44.002569+0500 HowICompare[4599:1223343] <ALPushNotificationService.m:138> APPLOZIC_02 Sync Call Completed
2018-09-04 20:14:44.003704+0500 HowICompare[4599:1223343] <ALUserDefaultsHandler.m:205> saving last Sync time in the preference ...1536074056470
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}
0
{
    data =     {
        "message_count" = 0;
        "notification_count" = 0;
        "update_count" = 1563;
    };
    message = "All Counts";
    status = 200;
}

**Comment by Sunilkumarr** [comment]
@najeeburrehman-brainx code looks fine for sending a message.

Do you have any sample project or your project where I can check can you share at support@applozic.com will check and get back?

**Comment by najeeburrehman-brainx** [comment]
Hi there,
Have a nice day ahead.
Please find the video attached. It is Applozic sample app and the video will elaborate you the problem I am facing, even your sample app have this problem.
Hope to hear from you soon.

Url of the video :  https://drive.google.com/open?id=18XPHTjQ73IXJWHF6h3dqq0liJ9-V73Ui

**Comment by Sunilkumarr** [comment]
its open channel right? for one to one, it will work.

In the open channel we don't store the messages in our local DB we fetch data from our server and show in UI. will check in open channel let you know

**Comment by najeeburrehman-brainx** [comment]
O really…. But in my first milestone I have to ship the working of open group in which every user of the app will be automatically added so they all can have chat with eachother. Please let me know the possible solution as soon as possible.

**Comment by Sunilkumarr** [comment]
In the open group, you don't need to add the members only one member will be there who creates that open group make sure you dont add the members in open group while creating.


if the user is not a member of that group also they can chat in that group 

You can launch the open group using below code 


**#import "ALChatManager.h"**


          ALChannelService *channelService = [[ALChannelService alloc] init];
            NSNumber *channelKey = @6731287; //pass channelKey here 
    
    [channelService  getChannelInformation:channelKey orClientChannelKey:nil withCompletion:^(ALChannel *alChannel) {
        if(alChannel){
            ALChatManager * chatManager = [[ALChatManager alloc] init];
            
            [chatManager launchChatForUserWithDisplayName:nil withGroupId:channelKey
                                       andwithDisplayName:nil andFromViewController:self];
            
            
        }
        
    }];

**NOTE:**

If your using our any API methods to load the conversation then once you check the chat call the below methods to load the conversations in `viewDidAppear`

 
`loadMessagesForOpenChannel` and `subscrbingChannel`

You can check the [link](https://github.com/AppLozic/Applozic-iOS-SDK/blob/master/sample-with-framework/Applozic/Applozic/ViewControllers/ALChatViewController.m#L380-L382) for the methods in github

**Comment by najeeburrehman-brainx** [comment]
Hi there,

I am using the custom UI and using your SDK methods to get the data. I have implement both of the methods  "loadMessagesForOpenChannel and subscrbingChannel” but still not getting messages after sending. Instead of these methods I have to delegate my controller to some class or nothing is required other than this..?

**Comment by Sunilkumarr** [comment]
Can you explain more about the issue where your not getting message is on receiver or sender side? 


if its sender side after going back by pressing back button are you calling that loadMessagesForOpenChannel to get the messages from the server in `viewDidAppear`?

**Comment by najeeburrehman-brainx** [comment]
I am not getting messages on the sender side. Yes I am calling loadMessagesForOpenChannel method in viewwillAppear.

**Comment by najeeburrehman-brainx** [comment]
As per my observation this method (i.e loadMessagesForOpenChannel) is also fetching the messages from the local DB of the device

**Comment by Sunilkumarr** [comment]
we have some issue if that user  is in the open channel we are not loading messages from the server it will not load the messages if he is a member of the channel 

Is the user who is sending a message to a member of the open channel or not? 

**Can you make sure that user who is chat will not be in that open channel?**

For the open channel, we fetch from the server directly display on UI

**Comment by najeeburrehman-brainx** [comment]
You have to provide some method that will do all the internal logic of your SDK I just have to call it with the message to send but I can’t find any thing like that.

**Comment by Sunilkumarr** [comment]
Who is sending a message in that channel is the user who is currntly created channel or some other user  ? 

There will be one  admin of that group who creates that open channel and other users who want to chat in that open channel will just load the channel and chat in that

**Comment by najeeburrehman-brainx** [comment]
Even your sample apps are showing this behaviour. Open groups don’t support live chat. Find the video on the given url of your sample app 
 Video : https://drive.google.com/open?id=1BX2U_VXzhkh-hDA9W6Yt3KwlRKuv3k5l

**Comment by najeeburrehman-brainx** [comment]
But in the loadMessagesForOpenChannel method you have a condition that the user can’t be the member of that group. Which is highlighted in the screenshot attached to it. If one have to be the admin of the group then this condition always fail for that user because ultimately admin would be the member of the group.

**Comment by najeeburrehman-brainx** [comment]
Hi Sunil,
Is live chat supported in the Open Group….?
I didn’t get the notification when the app is opened please guide me to get notified when the app is in foreground
 So to load the chat to get updated message.

**Comment by Sunilkumarr** [comment]
You can check this doc for notification of new message event and add message in your message list array

https://docs.google.com/document/d/109HgSc64hgsabOijqoAoFCRdGTT1CLNz97WCSdArft8/edit?usp=drivesdk

**Comment by najeeburrehman-brainx** [comment]
Hi Sunil,
Thanks for sharing the detail for getting new message notification but it’s not working. Even the notification is quite uncertain sometimes I get the notification and sometimes I didn’t. Why it is showing such a behaviour…?

**Comment by najeeburrehman-brainx** [comment]
Does the Open Channel message is being notified by the push notifications…? Because I am getting the push notification for the one-to-one chat but not for the Open Channel please guide me in this.

**Comment by Sunilkumarr** [comment]
Thanks for sharing the detail for getting new message notification but it’s not working. Even the notification is quite uncertain sometimes I get the notification and sometimes I didn’t. Why it is showing such a behaviour…?

-->there can be the case if the mqtt is disconnected have you reconnected again?

Check the code 

https://github.com/AppLozic/Applozic-iOS-SDK/blob/master/sample-with-framework/Applozic/Applozic/ViewControllers/ALChatViewController.m#L4079

You can take reference  from this class 

once the mqtt is connected it will call subscribe 

https://github.com/AppLozic/Applozic-iOS-SDK/blob/master/sample-with-framework/Applozic/Applozic/ViewControllers/ALChatViewController.m#L3986


check if the above code is implemented in your view controller 


For the open channel, you will get MQTT notification only APNS notifications won't come as user is not added in the open channel 

NOTE: only you will get messages if you have opened  the open channel once you close the open channel you don't get a messages notification as its directly connected with MQTT when you're in chat screen of the channel  next time once you open the chat will fetch all messages of the open channel to reload data

**Comment by najeeburrehman-brainx** [comment]
I don’t get notification of new message for Open Channel even the chat screen for the open channel is opened. I have made this view controller the ALMQTTConversationDelegate and conforms to the protocol and implement the methods of the delegate. Attached is the screenshot but I don’t get the callback of new message in this channel. In which method I get the callback of new message for Open Channel.

**Comment by Sunilkumarr** [comment]
You can send your view controller and share  us the complete logs once you send a message in the open channel and also open the same open channel in with different login user and share logs from receiver user in the text file will analyze  logs

**Comment by najeeburrehman-brainx** [comment]
Attached is the file you asked for which includes the send message logs  and receive message logs(not getting any callback but copy the logs after sending message from other device) and the view controller code.

**Comment by Sunilkumarr** [comment]
can't see those files and logs which you have attached can you check and attach again

**Comment by najeeburrehman-brainx** [comment]
Please could you guide me to get the unread count of the thread. In the threads listing now when I get the new Message notification then the channels information like unread count automatically get updated for the channel in which message is coming…?

**Comment by Sunilkumarr** [comment]
The shared link don't have muchs logs related could you share complete logs ? 

Please could you guide me to get the unread count of the thread. In the threads listing now when I get the new Message notification then the channels information like unread count automatically get updated for the channel in which message is coming…?

-->You can check the doc [link](https://docs.applozic.com/docs/ios-unread-count#section-individual-user) for how to get unread count you can listen for new message event notification from this [link](https://docs.applozic.com/docs/ios-unread-count#section-real-time-update-of-count) to update in your UI

**Comment by najeeburrehman-brainx** [comment]
The unread count always give the value 0 on “newMessage”  notification

**Comment by Sunilkumarr** [comment]
This is for open channel or one to one? and are you getting a new message event in open channel or not?

**Comment by najeeburrehman-brainx** [comment]
Hi Sunil,
It’s open Channel and I am getting new Message notification in both chats listing controller and in chatting controller. When I get the newMessage notification on the chats listing controller I get the information of the channel using “channelService.getChannelByKey(key)” but the channel it returns always gives the value 0 for unread count.

**Comment by Sunilkumarr** [comment]
we don't maintain the unread count for the open channel as users won't be in that groups

**Comment by najeeburrehman-brainx** [comment]
Hi Sunil,
How I get the previous messages with from some reference date (i.e. last fetched message date)

**Comment by najeeburrehman-brainx** [comment]
It will return the messages that have "createdTime" before  the “messageListRequest.endTimeStamp”  …..?

**Comment by najeeburrehman-brainx** [comment]
Please review your “ALMessageArrayWrapper” class it is not working fine. Sometimes it repeats the messages and sometimes it don’t append the date message at the top of the message list.

**Comment by najeeburrehman-brainx** [comment]
Can I get the list of all users against my Applozic Application key …?
I need it answer as early as possible.
Thanks

**Comment by Sunilkumarr** [comment]
It will return the messages that have "createdTime" before the “messageListRequest.endTimeStamp”  …..?  
ya this will give old messages first top 60 will load once you load for next with ceratedAtTime of top to pull then it will load next 60 messages 

Can I get the list of all users against my Applozic Application key …?

you can call the below api to get  the list of registred users 

           ALUserService * userService = [ALUserService new];
           [userService getListOfRegisteredUsersWithCompletion:^(NSError *error) {
        
           }];

**Comment by najeeburrehman-brainx** [comment]
Thanks for the quick response.

**Comment by najeeburrehman-brainx** [comment]
Please confirm the following information about groups :

Public Group : Only member of the group can add the user to the group or user can join itself to the public group.
Private Group : Only admin can add member to the group or the member can also add the new user to the group.

**Comment by Sunilkumarr** [comment]
You can check the link for following types and description https://docs.applozic.com/v1.0/reference#group-types

**Comment by Sunilkumarr** [comment]
Closing this issue as your able to receive the message and show in chat view if your not able to receive then fell free to open issue  .  if you have another query you can create an issue or you can write us at support@applozic.com
