### ISSUE TITLE
Swift 4.2 compatibility issue

### ISSUE THREAD

**Issue by prgorasiya** [AppLozic/Applozic-iOS-SDK#489]
Hi, I am updating Applozic framework to latest by manual installation method but I am facing swift 4.2 compatibility issue.

I am using Xcode 10.0 and my project is mainly based on Objective-C but all the new features are based on swift.
So when I try to build my project after updating Applozic framework to latest one I am getting this error.

`module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/paras/Downloads/Applozic-iOS-Chat-Samples-master/sampleapp-swift/Applozic.framework/Modules/Applozic.swiftmodule/x86_64.swiftmodule`

So now I am stuck because I can't use latest Applozic framework until you guys release a swift 4.2 compatible version.

Please let me know how can I resolve this issue.

Thanks

**Comment by Sunilkumarr** [comment]
@prgorasiya Hi,  We doing a release with swift support 4.2 will update once it's released

**Comment by Sunilkumarr** [comment]
@prgorasiya we have released new Apploizc  IOS SDK with support for swift 4.2. You can use our latest framework from this  link : https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks

**Comment by prgorasiya** [comment]
Thank you.
