### ISSUE TITLE
**Bugs** Contacts localized String incorrect in ALNewContactsViewController

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#500]
## Goals
View localized new contacts screen to select contacts to chat with.

## Expected Results
The title of the screen will be localized for the language used.

## Actual Results
The text remains as "Contacts" and is not localized. The issue is that the localised key is misspelled. It is used everywhere else as 'contactsTitle' but in this case is misspelled as 'contactsTitile'.

## Steps to Reproduce
Change Language of device, and load translations for the key. Observe. Contacts title does not change.

## Code Sample
```objective-c
[self.navigationItem setTitle:NSLocalizedStringWithDefaultValue(@"contactsTitile", nil, [NSBundle mainBundle], @"Contacts" , @"")];
```

Applozic SDK version: latest

Xcode version:9.4

iOS version: 11.4

Dependency manager + version: cocoapods 1.1.1

**Comment by mukeshthawani** [comment]
Thanks for reporting this @adamsrosco. Will get it fixed in one of the next releases.
