### ISSUE TITLE
Crash ALLogger.m

### ISSUE THREAD

**Issue by chanonly123** [AppLozic/Applozic-iOS-SDK#504]
Using Applozic (6.6.1) emulator iPhone XS - iOS 12.1

<img width="800" alt="screenshot 2018-12-24 at 2 19 37 pm" src="https://user-images.githubusercontent.com/13619184/50394998-6354ec00-0787-11e9-92bf-d3a3b43a3094.png">

**Comment by ShivamPokhriyal** [comment]
@chanonly123, 
Screenshot isn't much helpful. Can you share logs from XCode?

**Comment by mukeshthawani** [comment]
Closing the issue due to inactivity. Feel free to open if it's still crashing.
