### ISSUE TITLE
Crash ALHyperLabel.m

### ISSUE THREAD

**Issue by chanonly123** [AppLozic/Applozic-iOS-SDK#505]
Applozic (5.9.1)

<img width="497" alt="screenshot 2018-12-26 at 12 48 53 pm" src="https://user-images.githubusercontent.com/13619184/50436597-be641b80-090c-11e9-96fb-1231762081e0.png">

**Comment by ShivamPokhriyal** [comment]
Hello @chanonly123,

Thanks for sharing the issue. We are trying to reproduce it in our local. If possible, can you share the text with which you are getting this error?
