### ISSUE TITLE
Crash ALUtilityClass.m

### ISSUE THREAD

**Issue by chanonly123** [AppLozic/Applozic-iOS-SDK#507]
Applozic (5.9.1)

<img width="572" alt="screenshot 2018-12-27 at 6 54 39 pm" src="https://user-images.githubusercontent.com/13619184/50481777-6f4fe080-0a09-11e9-8b51-02c62039b18d.png">

[download crash_log](https://github.com/AppLozic/Applozic-iOS-SDK/files/2712514/crash_log.txt)

**Comment by Sunilkumarr** [comment]
Can you please share us your restrictWords.txt file
