### ISSUE TITLE
Crash ALCustomPickerViewController.swift line 236

### ISSUE THREAD

**Issue by chanonly123** [AppLozic/Applozic-iOS-SDK#509]
Sdk version 6.6.1

<img width="1095" alt="screenshot 2019-01-16 at 10 42 34 am" src="https://user-images.githubusercontent.com/13619184/51227734-a6b40c00-197b-11e9-9a6b-cabb9874a07d.png">

**Comment by ShivamPokhriyal** [comment]
Hello @chanonly123, 
We have fixed this issue in version 6.9.0
Please try in new version and reopen this if you still face this issue.

**Comment by chanonly123** [comment]
Ok. Thanks.
