### ISSUE TITLE
APNS wrong message

### ISSUE THREAD

**Issue by mumensh** [AppLozic/Applozic-iOS-SDK#514]
**Bugs**: 
There is an Id with the message that is sent from the portal, How can I remove it or disable sending it with the message.

## Expected Results
AnyHashable("aps"): {
    alert = "hi";
    badge = 8;
    "content-available" = 1;
    sound = default;
}]

## Actual Results
AnyHashable("aps"): {
    alert = "5bcc6924109194344ec2d656\n5b5b6fa95e4393347923c933: hi";
    badge = 8;
    "content-available" = 1;
    sound = default;
}]

## Steps to Reproduce
Just send a push notification.

Applozic SDK version: 6.7.1

Xcode version: 10.1

iOS version: 12

Dependency manager + version: Cocoapods 1.5.3

**Comment by mukeshthawani** [comment]
@mumensh thanks for sharing the details.

Can you share more details about your use case? Why you want to remove that id as that's what is used to identify the receiver who is sending the message.
