### ISSUE TITLE
logged in with multiple accounts

### ISSUE THREAD

**Issue by mano1337o** [AppLozic/Applozic-iOS-SDK#517]
Would it be possible to be logged in with two users at the same time, receiving real-time updates and notifications for both of the users ?

E.g: In a tabbed app, tab1 would show messages list of userA while tab2 would show messages of userB.

**Comment by Sunilkumarr** [comment]
@mano1337o Unfortunately you can't log in two users at a time and at a time you can't get two login  users notification  only one user notification you can see the notifications
