### ISSUE TITLE
could not find module 'Applozic' for architecture 'armv7'; found: i386, x86_64

### ISSUE THREAD

**Issue by ravi-dahmakan** [AppLozic/Applozic-iOS-SDK#535]
## Goals

I want to integrate Applozic in my app
## Expected Results

Applozic integrated successfully, successfully able to compile and build
## Actual Results

Could not archive - getting error - could not find module 'Applozic' for architecture 'armv7'; found: i386, x86_64
## Steps to Reproduce

Using this document https://docs.applozic.com/docs/ios-chat-sdk
1. I generated archive framework
2. Copied that framework from derived data and integrated it in my app.
3. On archive I get error: "could not find module 'Applozic' for architecture 'armv7'; found: i386, x86_64"
## Code Sample

Applozic SDK version: ?
6.17.1
Xcode version: ?
10.2.1
iOS version: ?
min. 9.0
Dependency manager + version: ?

**Comment by mukeshthawani** [comment]
Can you try [this](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/Frameworks/Applozic%206.17.1%20Archive) archive framework?

Make sure you are using the latest version of Xcode and Clean build before the archive.

**Comment by ravi-dahmakan** [comment]
@mukeshthawani thanks worked
