### ISSUE TITLE
error Error? domain: "Applozic" - code: create group

### ISSUE THREAD

**Issue by chandaboy786** [AppLozic/Applozic-iOS-SDK#537]
Hello,

I am creating channel using folloring api but some times applogic send me an error  

**error Error? domain: "Applozic"** 

Kindly let me know how can I fix this. we need to fix this issue asap.

alChannelService .createChannel(createName, orClientChannelKey: forumId , andMembersList: membersList, andImageLink: nil, channelType: Int16(PRIVATE.rawValue), andMetaData: nil, adminUser: nil) { (alChannel, error) in
            
            print(alChannel?.key.stringValue)
            
            if((error == nil)){
                print("Channel successfully created")
                
                
            }
            
        
            
            }

Applozic SDK version: Latest

Xcode version: 11

iOS version: 13.3

Dependency manager + version:

**Comment by chandaboy786** [comment]
Any Update???

**Comment by mukeshthawani** [comment]
Can you share complete code snippet? Like the `type` of `createName`, `forumId` etc.

Also, it will be better if you can send us all the logs from Xcode console. Please send the log file through email(support@applozic.com).

**Comment by chandaboy786** [comment]
createName is dynamic and when forum is created then I am sending that hex string to forumId.

alChannelService .createChannel(createName, orClientChannelKey: forumId , andMembersList: membersList, andImageLink: nil, channelType: Int16(PRIVATE.rawValue), andMetaData: nil, adminUser: nil) { (alChannel, error) in

        print(alChannel?.key.stringValue)
        
        if((error == nil)){
            print("Channel successfully created")
            
            
        }
        
    
        
        }

**Comment by mukeshthawani** [comment]
Thanks! Please send us complete Xcode logs, we'll check.

**Comment by chandaboy786** [comment]
Any update on this ?

**Comment by chandaboy786** [comment]
Any update on this ?

**Comment by chandaboy786** [comment]
@mukeshthawani xcode is giving me this error "error Error? domain: "Applozic", and here is the code

AlChannelService .createChannel(createName, orClientChannelKey: forumId , andMembersList: membersList, andImageLink: nil, channelType: Int16(PRIVATE.rawValue), andMetaData: nil, adminUser: nil) { (alChannel, error) in

        print(alChannel?.key.stringValue)
        
        if((error == nil)){
            print("Channel successfully created")    
        }
        }

where createName = "anything" , forumId = (unique hashString) & membersList = array of Ids

**Comment by Sunilkumarr** [comment]
By the error which you have shared, it's difficult to identify the issue.
 
Can you please share the complete logs from Xcode from the starting login process to createChannel  process to support@applozic.com.

**Comment by chandaboy786** [comment]
This is the code which I am using .. sometimes it is giving me this error don't know why

**Comment by Sunilkumarr** [comment]
Can you please share the complete logs when you get the error to our support email at support@applozic.com with applicationKey and login userId?
