### ISSUE TITLE
processFileUploadSucess crashes.

### ISSUE THREAD

**Issue by chandaboy786** [AppLozic/Applozic-iOS-SDK#538]
<img width="1434" alt="Screenshot 2020-02-03 at 7 58 31 PM" src="https://user-images.githubusercontent.com/57762214/73663578-afc76680-46bf-11ea-9d1f-69c36910d0bc.png">
<img width="1437" alt="Screenshot 2020-02-03 at 7 58 50 PM" src="https://user-images.githubusercontent.com/57762214/73663579-afc76680-46bf-11ea-9aad-8d92f6372550.png">

I am using this code but after uploading successfull it is giving me the attach output.

dbMessage.fileMetaInfo.blobKeyString = message.fileMeta.blobKey;
    dbMessage.fileMetaInfo.contentType = message.fileMeta.contentType;
    dbMessage.fileMetaInfo.createdAtTime = message.fileMeta.createdAtTime;
    dbMessage.fileMetaInfo.key = message.fileMeta.key;
    dbMessage.fileMetaInfo.name = message.fileMeta.name;
    NSLog(message.fileMeta.size);
    dbMessage.fileMetaInfo.size = message.fileMeta.size; // error in this line
    dbMessage.fileMetaInfo.suUserKeyString = message.fileMeta.userKey;

**Comment by chandaboy786** [comment]
2020-02-02 08:05:11.115940+0500 [1600:312784] -[__NSCFNumber _fastCStringContents:]: unrecognized selector sent to instance 0xe80e27e936779e38

///


2020-02-02 08:05:42.347777+0500 Minivnt[1600:312784] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber _fastCStringContents:]: unrecognized selector sent to instance 0xe80e27e936779e38'

**Comment by chandaboy786** [comment]
<img width="1440" alt="Screenshot 2020-02-03 at 8 19 58 PM" src="https://user-images.githubusercontent.com/57762214/73665242-98d64380-46c2-11ea-9503-7bdb15254c81.png">

[0]	(null)	@"size" : (long)1518571	

Sizetype is long and your library	is set as String

**Comment by chandaboy786** [comment]
<img width="1426" alt="Screenshot 2020-02-03 at 8 35 11 PM" src="https://user-images.githubusercontent.com/57762214/73666476-b3112100-46c4-11ea-8d36-7914dfcb046f.png">

when Upload Audio it is crashing as well.

**Comment by chandaboy786** [comment]
2020-02-02 08:44:27.717 Applozic : [ALChatViewController.m:2757] :: SEND_MSG_ERROR :: Error Domain=Applozic Code=1 "SomethingWentWrong" UserInfo={NSLocalizedDescription=SomethingWentWrong}


<img width="1144" alt="Screenshot 2020-02-03 at 8 45 06 PM" src="https://user-images.githubusercontent.com/57762214/73667534-38e19c00-46c6-11ea-8132-6f3162e8f686.png">

**Comment by chandaboy786** [comment]
<img width="1402" alt="Screenshot 2020-02-03 at 9 25 48 PM" src="https://user-images.githubusercontent.com/57762214/73670869-cf648c00-46cb-11ea-97b0-9a7719c097f3.png">
<img width="1120" alt="Screenshot 2020-02-03 at 9 25 55 PM" src="https://user-images.githubusercontent.com/57762214/73670871-cffd2280-46cb-11ea-85cc-e4bbfa1933fd.png">


it is giving nil value in self.outputFilePath

**Comment by chandaboy786** [comment]
any update?? 

We are using your framework on our 6 client application, so kindly fix this issue asap as our clients are waiting for chat fixes.

**Comment by mukeshthawani** [comment]
@chandaboy786 Thanks for sharing the details. You are creating a UI of your own? Or are you using our UI?

And can you share some steps to replicate this issue?

**Comment by chandaboy786** [comment]
Thanks for the reply,

actually I have just update Pod version of Applozic and when I run code and I have following issues

1. Your code using Old framework of Video **(MPMoviePlayerViewController)** **I have fixed this issue by own**
2.  When image/video is uploaded then in response your backend developer send **message.fileMeta.size** in **Long** variable instead of **String**, so that's why it is crashing **I have fixed this issue by own**
2020-02-02 08:05:42.347777+0500 Minivnt[1600:312784] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: **'-[__NSCFNumber _fastCStringContents:]:** unrecognized selector sent to instance 0xe80e27e936779e38'
3. When I tried to upload Audio then proceed audio fucntion app crashes at **CFRelease(pathextension)** and comment that line but after send audio to server it is giving an error 2020-02-02 08:44:27.717 Applozic : [ALChatViewController.m:2757] :: SEND_MSG_ERROR :: Error Domain=Applozic Code=1 "SomethingWentWrong" UserInfo={NSLocalizedDescription=SomethingWentWrong} **Tyring to fix but unable to fix**

I am using Xcode Version 11.3.1 (11C504) , also I have attach screenshot for reference.

Thanks

**Comment by chandaboy786** [comment]
@mukeshthawani if you guys need code then let me know I will send you code ;)


Thanks

**Comment by mukeshthawani** [comment]
We just tried sending audio messages in our sample app, and it's working fine. In case of custom UI, please use these APIs: https://docs.applozic.com/docs/ios-chat-message-api#section-send-an-attachment-message-in-one-to-one-chat

**Comment by chandaboy786** [comment]
@mukeshthawani it is working fine on our previous pod but when I update pod and run code on Latest IOS version then it is not giving me particular response

**Comment by mukeshthawani** [comment]
Yes, we tried using the latest version of our SDK and Xcode. Can you reproduce the same using this [sample app](https://github.com/AppLozic/Applozic-iOS-SDK/tree/master/sample-with-framework)?

**Comment by chandaboy786** [comment]
i am using pod update man, can you please share code of **CFRelease(pathextension)**  whole function so I can match with my current Applogiz code.

**Comment by Sunilkumarr** [comment]
The audio issue we have  already in our latest version maybe your using old version of applozic SDK 

This is the code you can use the get the mime type 

   ```
   NSString *fileExtension = [filePath pathExtension];
   NSString *uti = (__bridge_transfer NSString *)UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, (__bridge CFStringRef)fileExtension, NULL);
   NSString *mimeType
   NSString *mimeType  = (__bridge_transfer NSString *)UTTypeCopyPreferredTagWithClass((__bridge CFStringRef)uti, kUTTagClassMIMEType);
```
 here is the link of the code [link](https://github.com/AppLozic/Applozic-iOS-SDK/blob/master/sample-with-framework/Applozic/Applozic/Utilities/ALUtilityClass.m#L155-L163) can check this method reference

**Comment by chandaboy786** [comment]
Printing description of filePath:
(NSString *) filePath = <variable not available>

(lldb) po filePath
error: Couldn't materialize: couldn't get the value of variable filePath: variable not available
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression
(lldb) 

check this code it is giving nil, I have replace with your new code

<img width="1120" alt="Screenshot 2020-02-04 at 3 09 08 PM" src="https://user-images.githubusercontent.com/57762214/73735001-60854280-4760-11ea-8837-5908478e423c.png">

**Comment by Sunilkumarr** [comment]
In ALAudioAttachmentViewController.m find the method sendButtonAction and replace it with below code 
```
-(IBAction)sendButtonAction:(id)sender
{
    NSString * path = [recorder.url path];
    [self.audioAttchmentDelegate audioAttachment: path];
    [self.navigationController popViewControllerAnimated:YES];
}
```
Reference  :

https://github.com/AppLozic/Applozic-iOS-SDK/blob/6fb808b16e52967cb34111184de7db07b443b0be/sample-with-framework/Applozic/Applozic/ViewControllers/ALAudioAttachmentViewController.m#L119-L124

**Comment by chandaboy786** [comment]
NSURL *videoURL = info[UIImagePickerControllerMediaURL];
        //object.classVideoPath = [videoURL path]; // comment this line
        
        NSString *filePath = [ALImagePickerHandler saveVideoToDocDirectory:videoURL];
        NSLog(@"filePath %@",filePath);


<img width="1134" alt="Screenshot 2020-02-04 at 4 54 28 PM" src="https://user-images.githubusercontent.com/57762214/73742834-18b9e780-476f-11ea-8886-c1bd9f609b02.png">

**Comment by chandaboy786** [comment]
now it is not uploaded multiple video's. failed at exporting video...

**Comment by Sunilkumarr** [comment]
@chandaboy786  Is the audio one is working?

what is the error? what is the applozic pod version your using?

**Comment by chandaboy786** [comment]
Hello,
 

I have send build to QA, once they verify all senario then I will update you accordionly.
