### ISSUE TITLE
ITMS-90511: CFBundleIdentifier Collision

### ISSUE THREAD

**Issue by apurcaroiu** [AppLozic/Applozic-iOS-SDK#539]
Hi,

We integrated applozic swift library in an IOS native application.
While uploading it to app store test flight, it gets removed with below error:

We identified one or more issues with a recent delivery for your app, "app-name" 0.1.0 (1). Please correct the following issues, then upload again.

**ITMS-90511: CFBundleIdentifier Collision - The Info.plist CFBundleIdentifier value 'com.applozic.ApplozicSwift' of '-----.app/Frameworks/ApplozicSwift.framework' is already in use by another application.**

Is there anyhting we need to done to be able to upload the application and use the applozic framework ?

Thanks
Adrian

**Comment by mukeshthawani** [comment]
@apurcaroiu if you are using [ApplozicSwift](https://github.com/AppLozic/ApplozicSwift), then use CocoaPods for installation. Otherwise, you can change the bundle id before creating a framework.

**Comment by apurcaroiu** [comment]
We added manually the .xcodeproj as a an embeded framework, will the change of the bundle id from applozicswift to something else will solve the nested framework problem?

Thanks

**Comment by mukeshthawani** [comment]
Yeah, if you change the bundle id of the framework, then there won't be a bundle identifier collision.
