### ISSUE TITLE
New messages received when app is closed not counted when app launched

### ISSUE THREAD

**Issue by victormihaita** [AppLozic/Applozic-iOS-SDK#543]
I managed to integrate the Applozic service with our iOS app but I have one issue. 

When I open the app, I don’t get the latest messages that were received while the app was in the background or closed. I need this to refresh the list with channels opened and to set the badge in the app with the number of new messages received. 
This works correctly when the app is opened and I receive new messages. It also works after I open an individual channel and then close it. At that time the new messages comes in correctly (only while the app is in the foreground). @Sunilkumarr 

Applozic SDK version: latest

Xcode version: latest

iOS version: >11

**Comment by Sunilkumarr** [comment]
Hello Victor,
Can you share more details to support@applozic.com
1. Are you building your own UI using our API methods in IOS or you're using our pre-build UI in your project?
2.Share us app delegate file.
3. What is the exact version of Applozic SDK are you using?
