### ISSUE TITLE
Keyboard is not working properly

### ISSUE THREAD

**Issue by chandaboy786** [AppLozic/Applozic-iOS-SDK#555]
Hello,

I am using applozic but then i open keyboard on chat message its UI is messing. 

Kindly let me know about fixes.

**These are the functions which I am using right now**
![Simulator Screen Shot - New OS 13 6 - 2020-08-21 at 16 43 19](https://user-images.githubusercontent.com/57762214/90887262-76411900-e3cd-11ea-89ce-a00f462d8daf.png)
![Simulator Screen Shot - New OS 13 6 - 2020-08-21 at 16 43 22](https://user-images.githubusercontent.com/57762214/90887279-7b05cd00-e3cd-11ea-953e-8362c790c3a3.png)
![Simulator Screen Shot - New OS 13 6 - 2020-08-21 at 16 43 25](https://user-images.githubusercontent.com/57762214/90887283-7c36fa00-e3cd-11ea-9c59-e212355b0821.png)

// Setting up keyboard notifications.
- (void)registerForKeyboardNotifications
{
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(keyBoardWillShow:)
                                                 name:UIKeyboardWillShowNotification object:nil];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(keyBoardWillHide:)
                                                 name:UIKeyboardWillHideNotification object:nil];
}

- (void)removeRegisteredKeyboardNotifications
{
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:UIKeyboardWillShowNotification
                                                  object:nil];

}

//------------------------------------------------------------------------------------------------------------------
#pragma mark - Keyboard Post Notifacations
//------------------------------------------------------------------------------------------------------------------

-(void) keyBoardWillShow:(NSNotification *) notification
{
    NSString * theAnimationDuration = [self handleKeyboardNotification:notification];

    self.checkBottomConstraint.constant = -1 * keyboardEndFrame.size.height +
    self.bottomLayoutGuide.length;

    [UIView animateWithDuration:theAnimationDuration.doubleValue animations:^{
        [self.view layoutIfNeeded];
        [self scrollTableViewToBottomWithAnimation:YES];
    } completion:^(BOOL finished) {
        if (finished) {
            [self scrollTableViewToBottomWithAnimation:YES];
        }
    }];
}

-(void) keyBoardWillHide:(NSNotification *) notification
{
    NSString * theAnimationDuration = [self handleKeyboardNotification:notification];
    
    self.checkBottomConstraint.constant = 0;
//    self.noConversationLabel.frame = tempFrame;
    
    [UIView animateWithDuration:theAnimationDuration.doubleValue animations:^{
        [self.view layoutIfNeeded];
        
    }];
  
}

-(NSString *)handleKeyboardNotification:(NSNotification *) notification{
    
    NSDictionary * theDictionary = notification.userInfo;
    NSString * theAnimationDuration = [theDictionary valueForKey:UIKeyboardAnimationDurationUserInfoKey];
    
    keyboardEndFrame = [(NSValue *)[[notification userInfo] objectForKey:UIKeyboardFrameEndUserInfoKey] CGRectValue];
    
//    self.typingLabel.frame = CGRectMake(0,
//                                        keyboardEndFrame.origin.y - (self.typingMessageView.frame.size.height + typingIndicatorHeight + navigationWidth),
//                                        self.view.frame.size.width, typingIndicatorHeight);
    return theAnimationDuration;
}

**Comment by Sunilkumarr** [comment]
We have pod project see if you can replicate it in this Sample project 
https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/ApplozicCocoaPodDemo

You can open this and go to this folder ApplozicCocoaPodDemo and 
* Do the pod install in terminal and 
* Open file ChatOptionVC.m
[ChatOptionVC.m](
https://github.com/AppLozic/Applozic-iOS-Chat-Samples/blob/master/ApplozicCocoaPodDemo/ApplozicCocoaPodDemo/ChatOptionVC.m)

* Launch the group by passing groupId [here](https://github.com/AppLozic/Applozic-iOS-Chat-Samples/blob/master/ApplozicCocoaPodDemo/ApplozicCocoaPodDemo/ChatOptionVC.m#L47)

Or else you could drop us a mail at support@applozic.com

**Comment by Sunilkumarr** [comment]
Due to inactive closing, this issue feel free to reopen with the above details.
Thanks.
