### ISSUE TITLE
App Crashing while marking conversation as read after being idle for some times

### ISSUE THREAD

**Issue by devappbirds** [AppLozic/Applozic-iOS-SDK#556]
## Goals

When our users open the app after prolong time by clicking on message notification, app crashes on marking conversation as read

## Expected Results

App should not crash

## Actual Results

https://prnt.sc/ue05ot

## Steps to Reproduce

Make app idle for few hours, then open app from message notification

## Code Sample

Applozic SDK version: 7.9.0

Xcode version: 11.5

iOS version: All version

Dependency manager + version: Cocoapods

**Comment by Sunilkumarr** [comment]
We will look into it. If we found something on this will keep update here.

**Comment by Sunilkumarr** [comment]
As we have informed in support mail. Use the latest version should fix this. closing this issue  
https://docs.applozic.com/docs/ios-chat-sdk#automated-installation-using-cocoapods
