### ISSUE TITLE
Xcode12, 'ALUserService' has different definitions in different modules; first difference is definition in module 'Applozic.ALUserService' found return type is 'ALUserService *'

### ISSUE THREAD

**Issue by djlim0527** [AppLozic/Applozic-iOS-SDK#557]
## Goals

We use ApplozicSwift, the Applozic SDK.
An error occurs when building after Xcode12 update.

Error : " 'ALUserService' has different definitions in different modules; first difference is definition in module 'Applozic.ALUserService' found return type is 'ALUserService *' "

'ALUserService' Interface is declared in other Framework.
Built normally in Xcode 11.7.

Please check.

## Expected Results

Build success.

## Code Sample

Applozic SDK version: 7.9.1

ApplozicSwift SDK version: 5.10.0

Xcode version: 12.0

iOS version: All version

Dependency manager + version: Cocoapods 1.9.3+

**Comment by Sunilkumarr** [comment]
@djlim0527 We are able to run the project in Xcode 12 this is the sample project we tried with above configration https://github.com/AppLozic/ApplozicSwift

Can you please share any sample project?

**Comment by djlim0527** [comment]
@Sunilkumarr sample project (https://github.com/djlim0527/ApplozicSwift)
Please check in the demo project.

**Comment by Sunilkumarr** [comment]
Hello @djlim0527,  
There is an ongoing issue regarding the same issue this in Developer Forums for Xcode 12 https://developer.apple.com/forums/thread/658012

**Comment by djlim0527** [comment]
@Sunilkumarr 
I also checked the article on the developer forum.
Is this an Xcode12 bug? Are there any other solutions?

**Comment by Sunilkumarr** [comment]
Ya, it looks like an Xcode 12 bug. 

One way is until the Xcode bug is fixed you can point to the Applozic pod and ApplozicSwift pod spec.

 1. Make sure to point to the master [branch](https://github.com/AppLozic/ApplozicSwift/commits/master)  in your forked repo   and change the Applozic version in pod spec [file](https://github.com/AppLozic/ApplozicSwift/blob/master/ApplozicSwift.podspec#L27) and commit it in your forked repo 


     `` complete.dependency 'Applozic', '~> 7.9.1' ``
    
  ### Change it to 7.10.0 :

     complete.dependency 'Applozic', '~> 7.10.0' 

2.  In your pod file you can point to below Apploizc pod :

     ``pod 'Applozic', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'xcode-12-rename'
     ``
3. You will have to rename the occurs of the class name `ALUserService`  to  `ALApplozicUserService` in the ApplozicSwift   https://github.com/AppLozic/ApplozicSwift and commit in your forked repo in the different branch it in your account.

4.  Add this in your pod file to point pod spec
 Change the git URL and branch name to  Point to your forked repo and branch 

 `pod 'ApplozicSwift', :git => 'git-url-to-your-forked-repo', :branch => 'name-of-the-branch-where-you-have-commited-the-change-from-step-3' `

**Comment by djlim0527** [comment]
Thank you for answering this issue.
Today I updated to Xcode 12.0.1 (12A7300) version and it was build success.
The Xcode bug seems to be fixed.

Thank you very much for your answer.
