### ISSUE TITLE
Add SPM support

### ISSUE THREAD

**Issue by victormihaita** [AppLozic/Applozic-iOS-SDK#561]
Hello. I am migrating all my pods to SPM (Swift Package Manager) and Applozic is one of the few that don't support it. Could you please add this to the project? Thanks in advance

**Comment by Sunilkumarr** [comment]
Hello @victormihaita ,

Sorry for the late reply. 
Currntly dont have an exact timeline for when we will add this SPM.
But ya we will work on this soon will keep update.
