### ISSUE TITLE
Message not received on receiver side when using custom ui.

### ISSUE THREAD

**Issue by bhavikvwteam** [AppLozic/Applozic-iOS-SDK#567]
## Goals
 
I want to receive and send message using custom chat ui.

## Expected Results

When i send the message from the sender then on server i can see the sent message. But on receiver side, onMessageReceived() function not called.  In short i am not getting the message on receiver side. Although when using in Pre-built  ui then  onMessageReceived() function gets called on receiver side.

## Actual Results

onMessageReceived() function not called on receiver side.

## Steps to Reproduce

Just guide me to the right direction.

## Code Sample

Applozic SDK version: 8.1.0

Xcode version: 12.4

iOS version: 14.4

Dependency manager + version: ?

**Comment by Sunilkumarr** [comment]
Hi @bhavikvwteam,

* Verify if the delegate is set and conversation is subscribed  https://docs.applozic.com/docs/ios-real-time-update#connecting-to-publish
* Verify the push setup steps are done: https://docs.applozic.com/docs/ios-push-notification#build-your-ui-from-scratch---message-notification
* Check out the Sample for custom UI app delegate file for real-time events delegate callbacks are  implemented here is [link](https://github.com/AppLozic/Custom-UI-Sample/blob/master/IosCustomUiSdk/IosCustomUiSdk/AppDelegate.swift)

If your still not getting after verifying the above steps please share the below details :

* Complete logs to support@applozic.com starting from login to app till sending a message and receiving. Sender end and receiver end logs in a text file.
* Also share the sample code that is implemented for a chat.

**Comment by bhavikvwteam** [comment]
Okay i got it using "Verify if the delegate is set and conversation is subscribed". Thank you for the help.
